# ============================================================
# STEP 04 — Self-Attention and Contextual Representation
# ============================================================

# Core Idea

Representations can dynamically reinterpret each other.


The meaning or representation of an entity can change
depending on surrounding context.

This process is called:

        self-attention

------------------------------------------------------------
# Central Philosophy
------------------------------------------------------------

Don't think of it like:

        "words looking at words"

Instead:

        dynamic contextual interaction
between representations.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Representations are NOT always static.

Context can reshape:

    * interpretation
    * relevance
    * information flow
    * representation geometry

------------------------------------------------------------
# Self-Attention Intuition
------------------------------------------------------------

Each representation simultaneously acts as:

    * query
    * key
    * value

This allows representations to:

        dynamically interact with each other.





------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Self-attention creates:

        contextual representation transformation

------------------------------------------------------------
# Learning Goals
------------------------------------------------------------

By the end of this file you should understand:

    * self-attention
    * contextual representation
    * dynamic reinterpretation
    * attention interaction matrices
    * contextual aggregation
    * information blending
    * relational geometry

------------------------------------------------------------
# Glossary of Important Functions
------------------------------------------------------------

torch.matmul(A, B)
    Matrix multiplication.

torch.softmax(x, dim)
    Converts scores into normalized attention weights.

torch.sum(x, dim)
    Aggregates weighted information.

unsqueeze(dim)
    Adds an extra dimension for broadcasting.

transpose(dim0, dim1)
    Swaps tensor dimensions.

------------------------------------------------------------
# Glossary of Mathematical Concepts
------------------------------------------------------------

Dot Product:
        Measures vector alignment.

Softmax:
        Converts interaction scores into normalized weights.

Attention Matrix:
        Stores pairwise interaction strengths.

Contextual Representation:
        Representation updated using surrounding context.

------------------------------------------------------------


# ============================================================
# COMPLETE MATHEMATICAL FORMULATIONS
# Self-Attention and Contextual Representation
# ============================================================

------------------------------------------------------------
# 1. INPUT REPRESENTATIONS
------------------------------------------------------------

Suppose:

            X ∈ R^(n × d)

where:

    n = number of representations
    d = representation dimension

Example:

            X =
            [x₁
             x₂
             x₃
             ...
             xₙ]

Each row:

            x_i ∈ R^d

represents one entity.

------------------------------------------------------------
# 2. QUERY, KEY, VALUE PROJECTIONS
------------------------------------------------------------

Self-attention creates three learned projections:

            Q = XW_Q
            K = XW_K
            V = XW_V

where:

    W_Q ∈ R^(d × d_k)
    W_K ∈ R^(d × d_k)
    W_V ∈ R^(d × d_v)

------------------------------------------------------------
# Interpretation
------------------------------------------------------------

Q:
        query vectors
        ("what am I searching for?")

K:
        key vectors
        ("what information do I contain?")

V:
        value vectors
        ("what information should flow?")

------------------------------------------------------------
# 3. RELATIONAL MATCHING
------------------------------------------------------------

Compatibility between queries and keys:

                S = QK^T

Expanded element-wise:

            s_ij = q_i · k_j

where:

    q_i = query vector for entity i
    k_j = key vector for entity j

------------------------------------------------------------
# Dot Product Expansion
------------------------------------------------------------

For vectors:

        q_i = [q₁, q₂, ..., q_d]
        k_j = [k₁, k₂, ..., k_d]

Dot product:

        q_i · k_j = Σ(q_t k_t)

------------------------------------------------------------
# Interpretation
------------------------------------------------------------

Large score:
        strong relational compatibility

Small score:
        weak relational compatibility

------------------------------------------------------------
# 4. SCALED DOT-PRODUCT ATTENTION
------------------------------------------------------------

Scaled compatibility matrix:

                S_scaled =
                    QK^T / sqrt(d_k)

where:

    d_k = key dimension

------------------------------------------------------------
# Why Scaling?
------------------------------------------------------------

Without scaling:

    large vector dimensions may create
    excessively large dot products.

Scaling stabilizes:

    * gradients
    * numerical magnitude
    * optimization behavior

------------------------------------------------------------
# 5. SOFTMAX NORMALIZATION
------------------------------------------------------------

Attention weights:

        A = softmax(S_scaled)

Expanded element-wise:

                    exp(s_ij)
    a_ij = --------------------------
                 Σ_j exp(s_ij)

------------------------------------------------------------
# Properties
------------------------------------------------------------

Attention weights satisfy:

        0 ≤ a_ij ≤ 1

and:

        Σ_j a_ij = 1

------------------------------------------------------------
# Interpretation
------------------------------------------------------------

a_ij measures:

        how strongly representation i
        attends to representation j

------------------------------------------------------------
# 6. CONTEXTUAL AGGREGATION
------------------------------------------------------------

Final contextual representations:

                Y = AV

Expanded element-wise:

            y_i = Σ(a_ij v_j)

where:

    a_ij = attention weight
    v_j  = value vector

------------------------------------------------------------
# Interpretation
------------------------------------------------------------

Each output representation becomes:

        a weighted contextual mixture

of other representations.

------------------------------------------------------------
# 7. FULL SELF-ATTENTION EQUATION
------------------------------------------------------------
"""

In [1]:
import torch

torch.manual_seed(42)

# ============================================================
# SECTION 1 — INPUT REPRESENTATIONS
# ============================================================

Suppose we have a sequence of representations.

These may represent:

    * words
    * image patches
    * latent states
    * semantic embeddings

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

In self-attention:

        representations interact with each other.

In [2]:
tokens = [
    "animal",
    "tree",
    "cat",
    "river"
]

X = torch.tensor([
    [0.9, 0.8],    # animal
    [0.1, 0.2],    # tree
    [0.85, 0.75],  # cat
    [-0.8, -0.7]   # river
])

print("\nInput Representations:\n")
print(X)

print("\nTensor Shape:")
print(X.shape)


Input Representations:

tensor([[ 0.9000,  0.8000],
        [ 0.1000,  0.2000],
        [ 0.8500,  0.7500],
        [-0.8000, -0.7000]])

Tensor Shape:
torch.Size([4, 2])


Tensor shape:

            (4, 2)

means:

    4 representations
    2-dimensional representation space

# ============================================================
# SECTION 2 — QUERY, KEY, VALUE PROJECTIONS
# ============================================================

Self-attention creates:

    * queries
    * keys
    * values

from the same input representations.

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

Q = XW_Q
K = XW_K
V = XW_V

where:

    W_Q = query projection matrix
    W_K = key projection matrix
    W_V = value projection matrix

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

The same representations generate:

        interaction roles

In [3]:
W_Q = torch.tensor([
    [1.0, 0.0],
    [0.0, 1.0]
])

W_K = torch.tensor([
    [1.0, 0.0],
    [0.0, 1.0]
])

W_V = torch.tensor([
    [1.0, 0.0],
    [0.0, 1.0]
])

Q = torch.matmul(X, W_Q)
K = torch.matmul(X, W_K)
V = torch.matmul(X, W_V)

print("\nQuery Matrix:\n")
print(Q)

print("\nKey Matrix:\n")
print(K)

print("\nValue Matrix:\n")
print(V)


Query Matrix:

tensor([[ 0.9000,  0.8000],
        [ 0.1000,  0.2000],
        [ 0.8500,  0.7500],
        [-0.8000, -0.7000]])

Key Matrix:

tensor([[ 0.9000,  0.8000],
        [ 0.1000,  0.2000],
        [ 0.8500,  0.7500],
        [-0.8000, -0.7000]])

Value Matrix:

tensor([[ 0.9000,  0.8000],
        [ 0.1000,  0.2000],
        [ 0.8500,  0.7500],
        [-0.8000, -0.7000]])


Observe:

For simplicity:

        projection matrices are identity matrices.

So:

        Q ≈ K ≈ V ≈ X

------------------------------------------------------------
# Important Clarification
------------------------------------------------------------

Real transformers learn these projection matrices.

# ============================================================
# SECTION 3 — RELATIONAL MATCHING
# ============================================================

Self-attention computes pairwise compatibility
between representations.

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

Compatibility matrix:

            S = QK^T

------------------------------------------------------------
# Geometric Interpretation
------------------------------------------------------------

Large score:
        strong relational alignment

Small score:
        weak relational alignment

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Representations dynamically evaluate
their relevance to each other.

In [4]:
scores = torch.matmul(
    Q,
    K.transpose(0, 1)
)

print("\nCompatibility Score Matrix:\n")
print(scores)


Compatibility Score Matrix:

tensor([[ 1.4500,  0.2500,  1.3650, -1.2800],
        [ 0.2500,  0.0500,  0.2350, -0.2200],
        [ 1.3650,  0.2350,  1.2850, -1.2050],
        [-1.2800, -0.2200, -1.2050,  1.1300]])


Interpretation:

Row i:
        query representation

Column j:
        key representation

Each value measures:

        relational compatibility

# ============================================================
# SECTION 4 — SCALED ATTENTION SCORES
# ============================================================

Attention scores are scaled for numerical stability.

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

Scaled scores:

                S / sqrt(d_k)

where:

    d_k = key dimension

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Scaling prevents excessively large interaction values.

In [5]:
d_k = K.shape[1]

scaled_scores = scores / torch.sqrt(
    torch.tensor(float(d_k))
)

print("\nScaled Attention Scores:\n")
print(scaled_scores)


Scaled Attention Scores:

tensor([[ 1.0253,  0.1768,  0.9652, -0.9051],
        [ 0.1768,  0.0354,  0.1662, -0.1556],
        [ 0.9652,  0.1662,  0.9086, -0.8521],
        [-0.9051, -0.1556, -0.8521,  0.7990]])


Observe:

Scaling reduced score magnitude.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Stable geometry becomes important
for deep representation systems.

# ============================================================
# SECTION 5 — ATTENTION WEIGHT MATRIX
# ============================================================

Softmax converts scores into:

        attention weights

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Attention weights determine:

        interaction influence strength

In [6]:
attention_matrix = torch.softmax(
    scaled_scores,
    dim=1
)

print("\nAttention Weight Matrix:\n")
print(attention_matrix)


Attention Weight Matrix:

tensor([[0.3976, 0.1702, 0.3744, 0.0577],
        [0.2797, 0.2428, 0.2768, 0.2006],
        [0.3910, 0.1759, 0.3695, 0.0635],
        [0.1034, 0.2189, 0.1091, 0.5686]])


Interpretation:

Each row represents:

        how strongly one representation
        attends to all others.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Attention creates:

        dynamic interaction topology

# ============================================================
# SECTION 6 — CONTEXTUAL REPRESENTATION AGGREGATION
# ============================================================

Self-attention updates representations
through weighted contextual aggregation.

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

Contextual output:

                Y = AV

where:

    A = attention matrix
    V = value matrix

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Representations become mixtures of:

        contextual information

In [7]:
contextual_representations = torch.matmul(
    attention_matrix,
    V
)

print("\nContextual Representations:\n")
print(contextual_representations)


Contextual Representations:

tensor([[ 0.6470,  0.5926],
        [ 0.3508,  0.3395],
        [ 0.6328,  0.5807],
        [-0.2472, -0.1897]])


Observe:

Each representation was updated using:

        information from other representations

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Self-attention enables:

        contextual reinterpretation

# ============================================================
# SECTION 7 — REPRESENTATION TRANSFORMATION
# ============================================================

Compare:

    original representations
            vs
    contextual representations

------------------------------------------------------------
# Important Concept
------------------------------------------------------------

Self-attention transforms representations dynamically.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Meaning becomes:

        context-dependent geometry

In [8]:
print("\nOriginal Representations:\n")
print(X)

print("\nUpdated Contextual Representations:\n")
print(contextual_representations)


Original Representations:

tensor([[ 0.9000,  0.8000],
        [ 0.1000,  0.2000],
        [ 0.8500,  0.7500],
        [-0.8000, -0.7000]])

Updated Contextual Representations:

tensor([[ 0.6470,  0.5926],
        [ 0.3508,  0.3395],
        [ 0.6328,  0.5807],
        [-0.2472, -0.1897]])


Observe:

Representations changed after contextual interaction.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Self-attention allows representations to:

        reshape each other dynamically

# ============================================================
# SECTION 8 — INFORMATION FLOW INTERPRETATION
# ============================================================

Attention matrices simulate:

        information flow networks

------------------------------------------------------------
# Important Concept
------------------------------------------------------------

Strong attention pathway:
        strong information transfer

Weak attention pathway:
        weak information transfer

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Self-attention dynamically controls:

        representational influence propagation

In [9]:
print("\nInformation Flow Strengths:\n")

for i in range(len(tokens)):

    print(f"\n{tokens[i]} attends to:\n")

    for j in range(len(tokens)):

        print(
            f"    {tokens[j]}"
            f" : {attention_matrix[i][j]:.4f}"
        )


Information Flow Strengths:


animal attends to:

    animal : 0.3976
    tree : 0.1702
    cat : 0.3744
    river : 0.0577

tree attends to:

    animal : 0.2797
    tree : 0.2428
    cat : 0.2768
    river : 0.2006

cat attends to:

    animal : 0.3910
    tree : 0.1759
    cat : 0.3695
    river : 0.0635

river attends to:

    animal : 0.1034
    tree : 0.2189
    cat : 0.1091
    river : 0.5686


Observe:

Each representation distributes attention differently.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Self-attention creates:

        adaptive contextual interaction systems

# ============================================================
# SECTION 9 — CONTEXTUAL MEANING
# ============================================================

One of the deepest ideas in transformers:

representations become context-sensitive.

------------------------------------------------------------
# Example Intuition
------------------------------------------------------------

The meaning of:

        "bank"

depends on surrounding context.

Examples:

    * river bank
    * financial bank

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Self-attention enables:

        contextual reinterpretation

inside representation geometry.

In [10]:
bank_context_1 = torch.tensor([
    [0.9, 0.8],    # river
    [0.85, 0.75],  # bank
])

bank_context_2 = torch.tensor([
    [-0.8, -0.7],  # money
    [-0.75, -0.65] # bank
])

print("\nRiver Bank Context:\n")
print(bank_context_1)

print("\nFinancial Bank Context:\n")
print(bank_context_2)


River Bank Context:

tensor([[0.9000, 0.8000],
        [0.8500, 0.7500]])

Financial Bank Context:

tensor([[-0.8000, -0.7000],
        [-0.7500, -0.6500]])


Observe:

Context changes relational positioning.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Representations gain meaning through:

        contextual interaction geometry

# ============================================================
# SECTION 10 — SELF-ATTENTION IN MODERN AI
# ============================================================

Self-attention became one of the foundations
of modern AI systems.

------------------------------------------------------------
# Applications
------------------------------------------------------------

Self-attention is central for:

    * transformers
    * language models
    * vision transformers
    * multimodal systems
    * retrieval systems
    * generative AI

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Modern AI frequently relies on:

        contextual representation interaction

In [11]:
applications = [
    "Transformers",
    "Large Language Models",
    "Vision Transformers",
    "Multimodal AI",
    "Semantic Retrieval",
    "Generative Systems"
]

print("\nApplications of Self-Attention:\n")

for application in applications:

    print(f"- {application}")


Applications of Self-Attention:

- Transformers
- Large Language Models
- Vision Transformers
- Multimodal AI
- Semantic Retrieval
- Generative Systems


# ============================================================
# SECTION 11 — REPRESENTATION INTERACTION PIPELINE
# ============================================================

One of the deepest conceptual shifts in modern AI:

representations dynamically reinterpret each other.

------------------------------------------------------------
# Representation Flow
------------------------------------------------------------

            Representations
                    ↓
             Query / Key Matching
                    ↓
             Attention Weights
                    ↓
           Contextual Aggregation
                    ↓
        Updated Representations
                    ↓
        Contextual Meaning Formation

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Self-attention continuously reshapes:

        contextual representation geometry

In [12]:
print("\nSelf-Attention Pipeline:\n")

print("Representations")
print("       ↓")
print("Query-Key Matching")
print("       ↓")
print("Attention Matrix")
print("       ↓")
print("Weighted Aggregation")
print("       ↓")
print("Contextual Representations")
print("       ↓")
print("Dynamic Meaning")


Self-Attention Pipeline:

Representations
       ↓
Query-Key Matching
       ↓
Attention Matrix
       ↓
Weighted Aggregation
       ↓
Contextual Representations
       ↓
Dynamic Meaning


# ============================================================
# FINAL SUMMARY
# ============================================================

# Key Ideas Learned

1. Self-attention allows representations to interact dynamically

2. Queries, keys, and values emerge from the same representations

3. Dot-product matching measures relational compatibility

4. Attention matrices determine interaction strength

5. Self-attention creates contextual representations

6. Representations become context-dependent

7. Modern AI systems frequently rely on contextual geometry

------------------------------------------------------------
# Most Important Insight
------------------------------------------------------------

Self-attention enables representations to:

        dynamically reinterpret each other

through:

        contextual interaction geometry

inside representation space.

Meaning becomes:

        context-sensitive relational structure.

------------------------------------------------------------
# Connection to Future Topics
------------------------------------------------------------

This becomes foundational for:

    * transformers
    * language models
    * multimodal AI
    * generative systems
    * contextual reasoning