# ============================================================
# STEP 02 — Queries, Keys, and Relational Matching
# ============================================================

# Core Idea

Attention measures relational compatibility.

One of the deepest ideas in  attention systems:

representations dynamically determine
which other representations are relevant.

This relevance is computed through:

        relational matching

between vectors.

------------------------------------------------------------
# Central Philosophy
------------------------------------------------------------

Attention is fundamentally:

        similarity-driven interaction selection

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Queries and keys create a mechanism for:

        dynamic relational comparison

inside representation space.

------------------------------------------------------------
# Core Components
------------------------------------------------------------

Attention systems typically use:

    * Query vectors (Q)
    * Key vectors   (K)
    * Value vectors (V)

------------------------------------------------------------
# Intuition
------------------------------------------------------------

Query:
        "What information am I searching for?"

Key:
        "What kind of information do I contain?"

Value:
        "What information should be transferred?"

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

where:

    Q = query matrix
    K = key matrix
    V = value matrix

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Attention computes:

        relational compatibility

between representations.

------------------------------------------------------------
# Learning Goals
------------------------------------------------------------

By the end of this file you should understand:

    * queries
    * keys
    * values
    * relational matching
    * dot-product similarity
    * compatibility scores
    * dynamic interaction selection

------------------------------------------------------------

In [1]:
import torch

torch.manual_seed(42)

# ============================================================
# SECTION 1 — REPRESENTATION VECTORS
# ============================================================

Suppose we already have representation vectors.

These may represent:

    * words
    * image patches
    * latent states
    * semantic embeddings

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Attention systems compare representations
through relational geometry.

In [2]:
representations = torch.tensor([
    [0.9, 0.8],    # token 1
    [0.1, 0.2],    # token 2
    [0.85, 0.75],  # token 3
    [-0.8, -0.7]   # token 4
])

print("\nRepresentation Vectors:\n")
print(representations)


Representation Vectors:

tensor([[ 0.9000,  0.8000],
        [ 0.1000,  0.2000],
        [ 0.8500,  0.7500],
        [-0.8000, -0.7000]])


Each row becomes:

        one representation vector

inside representation space.

# ============================================================
# SECTION 2 — QUERY VECTORS
# ============================================================

A query vector represents:

        what information is being searched for

------------------------------------------------------------
# Intuition
------------------------------------------------------------

The query asks:

        "Which representations are relevant to me?"

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Queries define interaction intent.

In [3]:
query = torch.tensor([
    0.88,
    0.79
])

print("\nQuery Vector:\n")
print(query)


Query Vector:

tensor([0.8800, 0.7900])


Observe:

The query resembles:

    token 1
    token 3

This suggests those tokens may become relevant.

# ============================================================
# SECTION 3 — KEY VECTORS
# ============================================================

Key vectors represent:

        searchable representation signatures

------------------------------------------------------------
# Intuition
------------------------------------------------------------

A key answers:

        "What kind of information do I contain?"

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Keys enable relational matching.

In [4]:
keys = representations

print("\nKey Vectors:\n")
print(keys)


Key Vectors:

tensor([[ 0.9000,  0.8000],
        [ 0.1000,  0.2000],
        [ 0.8500,  0.7500],
        [-0.8000, -0.7000]])


In many simplified examples:

        keys ≈ representations

But in real transformers:

    queries, keys, and values are often
    learned projections.

# ============================================================
# SECTION 4 — DOT PRODUCT MATCHING
# ============================================================

Attention compares queries and keys using:

        dot-product interaction

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

Dot product:

            Q · K

Expanded:

        Σ(q_i k_i)

------------------------------------------------------------
# Geometric Interpretation
------------------------------------------------------------

Large dot product:
        strong alignment

Small dot product:
        weak alignment

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Dot products measure:

        relational compatibility

In [5]:
compatibility_scores = torch.matmul(
    keys,
    query
)

print("\nCompatibility Scores:\n")
print(compatibility_scores)


Compatibility Scores:

tensor([ 1.4240,  0.2460,  1.3405, -1.2570])


Observe:

Some keys produced larger scores.

These representations align more strongly
with the query.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Attention becomes:

        similarity-driven interaction selection

# ============================================================
# SECTION 5 — WHY SCALING IS NECESSARY
# ============================================================

Large vector dimensions may produce:

        extremely large dot products

------------------------------------------------------------
# Mathematical Scaling
------------------------------------------------------------

Scaled attention divides by:

                sqrt(d_k)

where:

    d_k = key dimension

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Scaling stabilizes interaction magnitude.

In [6]:
d_k = query.shape[0]

scaled_scores = compatibility_scores / torch.sqrt(
    torch.tensor(float(d_k))
)

print("\nScaled Compatibility Scores:\n")
print(scaled_scores)


Scaled Compatibility Scores:

tensor([ 1.0069,  0.1739,  0.9479, -0.8888])


Observe:

Scaling reduced score magnitude.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Stable numerical behavior becomes important
for deep attention systems.

# ============================================================
# SECTION 6 — SOFTMAX AS RELATIONAL NORMALIZATION
# ============================================================

Raw compatibility scores are converted into:

        attention weights

using softmax.

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------
softmax(x(i)) = e ^ x(i) / summation (e ^ x(j))
where:

    x(i) = input score for position i
    e^(x(i)) = exponential amplification

------------------------------------------------------------
# Important Property
------------------------------------------------------------

Softmax converts arbitrary scores into:

    * positive values
    * normalized weights
    * probability-like distributions

such that:

                Σ softmax(x(i)) = 1


------------------------------------------------------------
# Geometric Interpretation
------------------------------------------------------------

Softmax converts scores into:

        normalized influence strengths
Higher compatibility score:
        stronger interaction weight

Lower compatibility score:
        weaker interaction weight

------------------------------------------------------------
# Important Insight
------------------------------------------------------------
Softmax redistributes representational influence
across interacting representations.
Attention weights determine:

        interaction importance

In [7]:
attention_weights = torch.softmax(
    scaled_scores,
    dim=0
)

print("\nAttention Weights:\n")
print(attention_weights)

print("\nSum of Attention Weights:")
print(attention_weights.sum())


Attention Weights:

tensor([0.3956, 0.1720, 0.3729, 0.0594])

Sum of Attention Weights:
tensor(1.0000)


Observe:

Weights now form a probability-like distribution.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Attention redistributes representational influence.

# ============================================================
# SECTION 7 — VALUE VECTORS
# ============================================================

Value vectors contain:

        transferable information

------------------------------------------------------------
# Intuition
------------------------------------------------------------

Queries and keys decide:

        what is relevant

Values determine:

        what information flows

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Attention separates:

    * interaction matching
    * information transfer

In [8]:
values = torch.tensor([
    [1.0, 0.9],
    [0.1, 0.2],
    [0.95, 0.85],
    [-0.8, -0.7]
])

print("\nValue Vectors:\n")
print(values)


Value Vectors:

tensor([[ 1.0000,  0.9000],
        [ 0.1000,  0.2000],
        [ 0.9500,  0.8500],
        [-0.8000, -0.7000]])


Values may differ from keys.

In transformers:

    values are learned representations
    carrying transferable information.

# ============================================================
# SECTION 8 — WEIGHTED INFORMATION AGGREGATION
# ============================================================

Attention combines values using:

        attention weights

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

Attention output:

        y = Σ(a_i * v_i)

where:

    a_i = attention weight
    v_i = value vector

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Attention dynamically routes information.

In [9]:
attention_output = torch.sum(
    attention_weights.unsqueeze(1)
    * values,
    dim=0
)

print("\nAttention Output:\n")
print(attention_output)


Attention Output:

tensor([0.7196, 0.6659])


Observe:

More relevant values contributed more strongly.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Attention creates:

        adaptive information aggregation

# ============================================================
# SECTION 9 — FULL ATTENTION PIPELINE
# ============================================================

Attention systems perform:

        relational interaction routing

------------------------------------------------------------
# Full Pipeline
------------------------------------------------------------

            Query
                ↓
        Relational Matching
                ↓
        Compatibility Scores
                ↓
              Softmax
                ↓
        Attention Weights
                ↓
        Weighted Aggregation
                ↓
         Contextual Output

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Attention dynamically determines:

        which information matters

In [10]:
print("\nAttention Pipeline:\n")

print("Query")
print("   ↓")
print("Key Matching")
print("   ↓")
print("Compatibility Scores")
print("   ↓")
print("Softmax")
print("   ↓")
print("Attention Weights")
print("   ↓")
print("Weighted Values")
print("   ↓")
print("Contextual Representation")


Attention Pipeline:

Query
   ↓
Key Matching
   ↓
Compatibility Scores
   ↓
Softmax
   ↓
Attention Weights
   ↓
Weighted Values
   ↓
Contextual Representation


# ============================================================
# SECTION 10 — ATTENTION AS GEOMETRIC INTERACTION
# ============================================================

One of the deepest ideas in modern AI:

attention operates through:

        relational geometry

------------------------------------------------------------
# Important Concept
------------------------------------------------------------

Attention does NOT explicitly store rules like:

    "this word is important"

Instead:

    geometric compatibility determines
    interaction strength dynamically.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Modern attention systems frequently operate through:

        similarity-driven geometry

In [11]:
print("\nCore Attention Principle:\n")

print("Representations")
print("       ↓")
print("Geometric Compatibility")
print("       ↓")
print("Dynamic Interaction Weights")
print("       ↓")
print("Adaptive Information Flow")


Core Attention Principle:

Representations
       ↓
Geometric Compatibility
       ↓
Dynamic Interaction Weights
       ↓
Adaptive Information Flow


# ============================================================
# FINAL SUMMARY
# ============================================================

# Key Ideas Learned

1. Attention measures relational compatibility

2. Queries represent interaction intent

3. Keys represent searchable signatures

4. Dot products measure geometric alignment

5. Softmax converts compatibility into influence weights

6. Values carry transferable information

7. Attention dynamically routes information

------------------------------------------------------------
# Most Important Insight
------------------------------------------------------------

Attention systems dynamically determine:

        which representations
        should interact strongly

through:

        geometric similarity matching

inside representation space.

------------------------------------------------------------
# Connection to Future Topics
------------------------------------------------------------

This becomes foundational for:

    * self-attention
    * transformers
    * contextual representations
    * language models
    * multimodal interaction systems