In [1]:
import torch

In [2]:
BREAK_SIZE = 70

In [6]:
print("=" * BREAK_SIZE)
print("PYTORCH COMPARISON OPERATIONS PLAYGROUND")
print("=" * BREAK_SIZE)

print(f"PyTorch Version : {torch.__version__}")

print("=" * BREAK_SIZE)

PYTORCH COMPARISON OPERATIONS PLAYGROUND
PyTorch Version : 2.10.0+cpu


In [7]:
####################################################################
# BASE TENSORS
####################################################################

x = torch.tensor([
    [1, 5, 3],
    [7, 2, 9]
])

y = torch.tensor([
    [1, 4, 8],
    [6, 2, 10]
])

print("Tensor x :")
print(x)

print("\nTensor y :")
print(y)

Tensor x :
tensor([[1, 5, 3],
        [7, 2, 9]])

Tensor y :
tensor([[ 1,  4,  8],
        [ 6,  2, 10]])


####################################################################
# torch.eq()
####################################################################


####################################################################
# DESCRIPTION:
#
# eq = equal
#
# Compares corresponding elements.
#
# Returns:
# True  -> if equal
# False -> otherwise
#
####################################################################

####################################################################
# MATHEMATICAL FORMULATION:
#
# z_ij = (x_ij == y_ij)
#
####################################################################

####################################################################
# BASIC ALGORITHM:
#
# for every element:
#
# if x_ij == y_ij:
#     True
# else:
#     False
#
####################################################################

In [8]:
print("\n" + "#" * BREAK_SIZE)
print("method torch.eq()")
z1 = torch.eq(x, y)

print(z1)


######################################################################
method torch.eq()
tensor([[ True, False, False],
        [False,  True, False]])


####################################################################
# torch.ne()
####################################################################


####################################################################
# DESCRIPTION:
#
# ne = not equal
#
# Returns True where elements differ.
#
####################################################################

####################################################################
# MATHEMATICAL FORMULATION:
#
# z_ij = (x_ij != y_ij)
#
####################################################################

####################################################################
# BASIC ALGORITHM:
#
# if x_ij != y_ij:
#     True
# else:
#     False
#
####################################################################

In [9]:
print("\n" + "#" * BREAK_SIZE)
print("method torch.ne()")

z2 = torch.ne(x, y)

print(z2)


######################################################################
method torch.ne()
tensor([[False,  True,  True],
        [ True, False,  True]])


####################################################################
# torch.gt()
####################################################################



####################################################################
# DESCRIPTION:
#
# gt = greater than
#
####################################################################

####################################################################
# MATHEMATICAL FORMULATION:
#
# z_ij = (x_ij > y_ij)
#
####################################################################

####################################################################
# BASIC ALGORITHM:
#
# if x_ij > y_ij:
#     True
# else:
#     False
#
####################################################################

In [10]:
print("\n" + "#" * BREAK_SIZE)
print("method torch.gt()")
z3 = torch.gt(x, y)

print(z3)


######################################################################
method torch.gt()
tensor([[False,  True, False],
        [ True, False, False]])


####################################################################
# torch.lt()
####################################################################



####################################################################
# DESCRIPTION:
#
# lt = less than
#
####################################################################

####################################################################
# MATHEMATICAL FORMULATION:
#
# z_ij = (x_ij < y_ij)
#
####################################################################

####################################################################
# BASIC ALGORITHM:
#
# if x_ij < y_ij:
#     True
# else:
#     False
#
####################################################################

print("\n" + "#" * BREAK_SIZE)
print("method torch.lt()")
z4 = torch.lt(x, y)

print(z4)

####################################################################
# torch.ge()
####################################################################


####################################################################
# DESCRIPTION:
#
# ge = greater than or equal
#
####################################################################

####################################################################
# MATHEMATICAL FORMULATION:
#
# z_ij = (x_ij >= y_ij)
#
####################################################################

####################################################################
# BASIC ALGORITHM:
#
# if x_ij >= y_ij:
#     True
# else:
#     False
#
####################################################################

print("\n" + "#" * BREAK_SIZE)
print("method torch.ge()")
z5 = torch.ge(x, y)

print(z5)

####################################################################
# torch.le()
####################################################################



####################################################################
# DESCRIPTION:
#
# le = less than or equal
#
####################################################################

####################################################################
# MATHEMATICAL FORMULATION:
#
# z_ij = (x_ij <= y_ij)
#
####################################################################

####################################################################
# BASIC ALGORITHM:
#
# if x_ij <= y_ij:
#     True
# else:
#     False
#
####################################################################

In [13]:
print("\n" + "#" * BREAK_SIZE)
print("method torch.le()")
z6 = torch.le(x, y)

print(z6)


######################################################################
method torch.le()
tensor([[ True, False,  True],
        [False,  True,  True]])


####################################################################
# torch.where()
####################################################################


####################################################################
# DESCRIPTION:
#
# Conditional selection operation.
#
# Selects values depending on condition.
#
####################################################################

####################################################################
# MATHEMATICAL FORMULATION:
#
# z_ij =
#
#     a_ij   if condition is True
#
#     b_ij   otherwise
#
####################################################################

####################################################################
# BASIC ALGORITHM:
#
# if condition:
#     select from tensor A
# else:
#     select from tensor B
#
####################################################################

In [14]:
print("\n" + "#" * BREAK_SIZE)
print("method torch.where()")
condition = x > y

print("Condition (x > y) :")
print(condition)

z7 = torch.where(condition, x, y)

print("\nSelected tensor :")
print(z7)


######################################################################
method torch.where()
Condition (x > y) :
tensor([[False,  True, False],
        [ True, False, False]])

Selected tensor :
tensor([[ 1,  5,  8],
        [ 7,  2, 10]])


####################################################################
# PRACTICAL EXAMPLE
####################################################################



####################################################################
# ReLU-like behavior using torch.where()
####################################################################

In [12]:
print("\n" + "#" * BREAK_SIZE)
print("PRACTICAL EXAMPLE")
sample = torch.tensor([
    [-3.0, -1.0, 2.0],
    [4.0, -5.0, 6.0]
])

print("Original Tensor :")
print(sample)

relu_like = torch.where(
    sample > 0,
    sample,
    torch.tensor(0.0)
)

print("\nReLU-like Output :")
print(relu_like)


######################################################################
PRACTICAL EXAMPLE
Original Tensor :
tensor([[-3., -1.,  2.],
        [ 4., -5.,  6.]])

ReLU-like Output :
tensor([[0., 0., 2.],
        [4., 0., 6.]])


####################################################################
# Important Insight:
#
# torch.where() is extremely important in:
#
# - masking
# - transformers
# - attention systems
# - filtering
# - conditional tensor operations
# - reinforcement learning
#
####################################################################

####################################################################
# FINAL SUMMARY
####################################################################

In [15]:
print("\n" + "=" * BREAK_SIZE)
print("COMPARISON OPERATIONS SUMMARY")
print("=" * BREAK_SIZE)

print("""
Comparison operations create BOOLEAN tensors.

True  -> condition satisfied
False -> condition failed

These operations are foundational for:

- masking
- filtering
- conditional selection
- attention mechanisms
- thresholding
- classification systems
- logical tensor operations
""")

print("=" * BREAK_SIZE)


COMPARISON OPERATIONS SUMMARY

Comparison operations create BOOLEAN tensors.

True  -> condition satisfied
False -> condition failed

These operations are foundational for:

- masking
- filtering
- conditional selection
- attention mechanisms
- thresholding
- classification systems
- logical tensor operations

