# # PyTorch Variable Operations Playground
#
# In this notebook/script we explore:
#
# - tensor.requires_grad_()
# - tensor.detach()
# - tensor.clone()
#
# These operations are deeply connected to:
#
# - autograd
# - computational graphs
# - gradient flow
# - memory management
# - tensor tracking
#
# They are extremely important in:
#
# - neural networks
# - reinforcement learning
# - transformers
# - diffusion models
# - latent semantic systems

In [2]:
import torch

BREAK_SIZE = 80

# # Base Tensor
#
# We first create a tensor WITHOUT gradient tracking.

In [30]:
x = torch.tensor([1.0, 2.0, 3.0])

print("=" * BREAK_SIZE)
print("BASE TENSOR")
print("=" * BREAK_SIZE)

print(x)

print("\nrequires_grad :")
print(x.requires_grad)

BASE TENSOR
tensor([1., 2., 3.])

requires_grad :
False


# # tensor.requires_grad_()
#
# ## DESCRIPTION
#
# Enables gradient tracking IN-PLACE.
#
# The underscore `_` means:
#
# > modify the existing tensor directly.
#
# ---
#
# ## MATHEMATICAL IDEA
#
# Suppose:
#
# y = f(x)
#
# We want:
#
# dy/dx
#
# Then:
#
# x must participate in the computational graph.
#
# requires_grad=True tells PyTorch:
#
# > "Track operations on this tensor."
#
# ---
#
# ## BASIC ALGORITHM
#
# 1. Mark tensor as differentiable
# 2. Record future operations
# 3. Build computational graph
# 4. Enable backpropagation

In [31]:
print("\n" + "#" * BREAK_SIZE)
print("method tensor.requires_grad_()")

x.requires_grad_()

print("\nTensor x :")
print(x)

print("\nrequires_grad :")
print(x.requires_grad)


################################################################################
method tensor.requires_grad_()

Tensor x :
tensor([1., 2., 3.], requires_grad=True)

requires_grad :
True


# # Build Computational Graph
#
# ## Mathematical Function
#
# y = x² + 2x
#
# ## Derivative
#
# dy/dx = 2x + 2

In [32]:
y = x**2 + 2*x

print("\nTensor y :")
print(y)

print("\nGradient function :")
print(y.grad_fn)


Tensor y :
tensor([ 3.,  8., 15.], grad_fn=<AddBackward0>)

Gradient function :


# # Backpropagation
#
# We now compute:
#
# dy/dx

In [33]:
print("\n" + "#" * BREAK_SIZE)
print("BACKPROPAGATION")

loss = y.sum()

loss.backward()

print("\nGradient of x :")
print(x.grad)


################################################################################
BACKPROPAGATION

Gradient of x :
tensor([4., 6., 8.])


# # Mathematical Verification
#
# For:
#
# y = x² + 2x
#
# dy/dx = 2x + 2
#
# If:
#
# x = [1, 2, 3]
#
# Then:
#
# dy/dx =
#
# [4, 6, 8]

# # tensor.detach()
#
# ## DESCRIPTION
#
# Creates tensor detached from computational graph.
#
# Detached tensor:
#
# - shares same memory
# - does NOT track gradients
# - breaks gradient propagation
#
# ---
#
# ## MATHEMATICAL IDEA
#
# Suppose:
#
# z = g(y)
#
# Normally:
#
# dz/dx propagates through y
#
# But detach():
#
# cuts graph connection
#
# So:
#
# dz/dx stops propagating.
#
# ---
#
# ## BASIC ALGORITHM
#
# 1. Create view of tensor
# 2. Remove graph tracking
# 3. Preserve underlying data
# 4. Prevent gradient flow

In [34]:
print("\n" + "#" * BREAK_SIZE)
print("method tensor.detach()")

a = torch.tensor(
    [1.0, 2.0, 3.0],
    requires_grad=True
)

b = a * 2

print("\nTensor b :")
print(b)

print("\nGradient tracking :")
print(b.requires_grad)


################################################################################
method tensor.detach()

Tensor b :
tensor([2., 4., 6.], grad_fn=<MulBackward0>)

Gradient tracking :
True


In [35]:
c = b.detach()

print("\nDetached tensor c :")
print(c)

print("\nGradient tracking :")
print(c.requires_grad)


Detached tensor c :
tensor([2., 4., 6.])

Gradient tracking :
False


In [15]:
# # Important Observation
#
# c:
#
# - still contains same values
# - but no longer participates in autograd

In [36]:
print("\nGradient function of b :")
print(b.grad_fn)

print("\nGradient function of c :")
print(c.grad_fn)


Gradient function of b :

Gradient function of c :
None


# # Memory Sharing Demonstration
#
# detach() shares memory with original tensor.

In [37]:
print("\n" + "#" * BREAK_SIZE)
print("MEMORY SHARING DEMONSTRATION")

print("\nOriginal c :")
print(c)

b[0] = 999

print("\nModified b :")
print(b)

print("\nDetached c after modifying b :")
print(c)


################################################################################
MEMORY SHARING DEMONSTRATION

Original c :
tensor([2., 4., 6.])

Modified b :
tensor([999.,   4.,   6.], grad_fn=<CopySlices>)

Detached c after modifying b :
tensor([999.,   4.,   6.])


# # Important Insight
#
# detach() does NOT copy memory.
#
# It only disconnects autograd graph.

# # tensor.clone()
#
# ## DESCRIPTION
#
# Creates COPY of tensor.
#
# Unlike detach():
#
# clone():
#
# - allocates new memory
# - copies values
#
# ---
#
# ## MATHEMATICAL IDEA
#
# clone():
#
# creates independent tensor:
#
# x_clone = x
#
# but physically stored separately.
#
# ---
#
# ## BASIC ALGORITHM
#
# 1. Allocate new memory
# 2. Copy tensor values
# 3. Preserve tensor structure
# 4. Return independent tensor

In [21]:
print("\n" + "#" * BREAK_SIZE)
print("method tensor.clone()")

p = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

print("\nOriginal tensor p :")
print(p)

q = p.clone()

print("\nCloned tensor q :")
print(q)


################################################################################
method tensor.clone()

Original tensor p :
tensor([[1., 2.],
        [3., 4.]])

Cloned tensor q :
tensor([[1., 2.],
        [3., 4.]])


In [22]:
# # Independent Memory Demonstration
#
# clone() creates separate memory.

In [23]:
p[0][0] = 999

print("\nModified p :")
print(p)

print("\nCloned q after modifying p :")
print(q)


Modified p :
tensor([[999.,   2.],
        [  3.,   4.]])

Cloned q after modifying p :
tensor([[1., 2.],
        [3., 4.]])


In [24]:
# # Important Observation
#
# q did NOT change.
#
# Therefore:
#
# clone() copied memory.

In [25]:
# # clone() + detach()
#
# This combination is EXTREMELY common.
#
Why?
#
# detach():
# - removes graph tracking
#
# clone():
# - creates independent memory
#
# Together:
#
# safe independent tensor copy.

Object `Why` not found.


In [26]:
print("\n" + "#" * BREAK_SIZE)
print("clone() + detach()")

u = torch.tensor(
    [1.0, 2.0, 3.0],
    requires_grad=True
)

v = u.clone().detach()

print("\nTensor u :")
print(u)

print("\nTensor v :")
print(v)

print("\nv requires_grad :")
print(v.requires_grad)


################################################################################
clone() + detach()

Tensor u :
tensor([1., 2., 3.], requires_grad=True)

Tensor v :
tensor([1., 2., 3.])

v requires_grad :
False


In [27]:
# # Why This Pattern Matters
#
# Frequently used in:
#
# - target networks
# - reinforcement learning
# - inference pipelines
# - tensor snapshots
# - stable latent representations

In [28]:
# # FINAL SUMMARY

In [29]:
print("\n" + "=" * BREAK_SIZE)
print("VARIABLE OPERATIONS SUMMARY")
print("=" * BREAK_SIZE)

print("""
1. requires_grad_()
   -> enables gradient tracking

2. detach()
   -> disconnects tensor from graph
   -> shares memory

3. clone()
   -> creates independent memory copy

Important Deep Learning Uses:

- autograd control
- memory management
- stable inference
- reinforcement learning
- transformer pipelines
- latent state preservation
""")

print("=" * BREAK_SIZE)


VARIABLE OPERATIONS SUMMARY

1. requires_grad_()
   -> enables gradient tracking

2. detach()
   -> disconnects tensor from graph
   -> shares memory

3. clone()
   -> creates independent memory copy

Important Deep Learning Uses:

- autograd control
- memory management
- stable inference
- reinforcement learning
- transformer pipelines
- latent state preservation

