# ============================================================
# STEP 04 — Projection and Dimensionality
# ============================================================

# Core Idea

High-dimensional systems can be projected
into observable structure.

Modern AI systems frequently operate in:

    * 64 dimensions
    * 128 dimensions
    * 768 dimensions
    * thousands of dimensions

Humans cannot directly visualize such spaces.

Projection allows us to:

        observe structure indirectly.

------------------------------------------------------------
# Central Philosophy
------------------------------------------------------------

Projection is NOT the original structure.

Projection is:

        a lower-dimensional view
        of higher-dimensional geometry.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Visualization is always an approximation.

Projected geometry may:

    * preserve some relationships
    * distort other relationships

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

Suppose:

            x ∈ R^n

is an n-dimensional vector.

Projection transforms:

            x → y

where:

            y ∈ R^m

and:

            m < n

------------------------------------------------------------
# Learning Goals
------------------------------------------------------------

By the end of this file you should understand:

    * dimensionality
    * projection systems
    * dimensional reduction
    * information compression
    * projection distortion
    * observable geometry
    * low-dimensional views

------------------------------------------------------------

In [1]:
import torch

torch.manual_seed(42)

# ============================================================
# SECTION 1 — HIGH-DIMENSIONAL REPRESENTATIONS
# ============================================================

Real AI systems operate in high-dimensional spaces.

------------------------------------------------------------
# Mathematical Form
------------------------------------------------------------

A high-dimensional vector:

        x = [x1, x2, x3, ..., xn]

where:

    n may be very large.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Humans struggle to visualize beyond:

    * 2D
    * 3D

But AI systems routinely operate in:

    hundreds or thousands of dimensions.

In [2]:
high_dim_vectors = torch.randn(5, 8)

print("\nHigh-Dimensional Representation Tensor:\n")
print(high_dim_vectors)

print("\nTensor Shape:")
print(high_dim_vectors.shape)


High-Dimensional Representation Tensor:

tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431, -1.6047],
        [-0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594, -0.7688,  0.7624],
        [ 1.6423, -0.1596, -0.4974,  0.4396, -0.7581,  1.0783,  0.8008,  1.6806],
        [ 0.0349,  0.3211,  1.5736, -0.8455,  1.3123,  0.6872, -1.0892, -0.3553],
        [-1.4181,  0.8963,  0.0499,  2.2667,  1.1790, -0.4345, -1.3864, -1.2862]])

Tensor Shape:
torch.Size([5, 8])


Tensor shape:

                (5, 8)

means:

    5 entities
    8-dimensional representation space

------------------------------------------------------------
# Important Clarification
------------------------------------------------------------

Even though we cannot visualize 8D space directly:

    geometry still exists mathematically.

# ============================================================
# SECTION 2 — WHY PROJECTION IS NECESSARY
# ============================================================

Humans need lower-dimensional views.

Projection creates:

        observable approximations

of high-dimensional structure.

------------------------------------------------------------
# Projection Idea
------------------------------------------------------------

Suppose we have:

            x ∈ R^8

Projection may create:

            y ∈ R^2

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Projection compresses information.

Some structure survives.

Some structure is lost.

In [3]:
print("\nOriginal 8D Vector:\n")
print(high_dim_vectors[0])

projected_vector = high_dim_vectors[0][:2]

print("\nProjected 2D Vector:\n")
print(projected_vector)


Original 8D Vector:

tensor([ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431, -1.6047])

Projected 2D Vector:

tensor([1.9269, 1.4873])


Here we performed a very simple projection:

        first 8 dimensions
                ↓
            first 2 dimensions

------------------------------------------------------------
# Important Clarification
------------------------------------------------------------

Real dimensionality reduction methods are usually
more sophisticated than simple slicing.

But the central idea remains:

        high dimensions
                ↓
        lower-dimensional view

# ============================================================
# SECTION 3 — PROJECTION AS INFORMATION COMPRESSION
# ============================================================

Projection compresses representation information.

------------------------------------------------------------
# Mathematical Interpretation
------------------------------------------------------------

Projection often reduces:

    * dimensional complexity
    * storage requirements
    * observable difficulty

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Compression usually introduces:

        information loss

This creates a tradeoff between:

    * simplicity
    * fidelity

In [4]:
original_vector = torch.tensor([
    2.4,
    -1.1,
    0.9,
    4.2,
    -3.0,
    1.5
])

compressed_vector = original_vector[:2]

print("\nOriginal 6D Vector:\n")
print(original_vector)

print("\nCompressed 2D Projection:\n")
print(compressed_vector)


Original 6D Vector:

tensor([ 2.4000, -1.1000,  0.9000,  4.2000, -3.0000,  1.5000])

Compressed 2D Projection:

tensor([ 2.4000, -1.1000])


Observe:

The projected vector contains only part
of the original information.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Projection simplifies structure.

But simplification may distort relationships.

# ============================================================
# SECTION 4 — DISTANCE DISTORTION
# ============================================================

Projection can change geometric relationships.

------------------------------------------------------------
# Important Concept
------------------------------------------------------------

Distances in projected space may differ from:

        original high-dimensional distances

------------------------------------------------------------
# Mathematical Idea
------------------------------------------------------------

Suppose:

        d_high(a,b)

is original distance.

After projection:

        d_low(a,b)

may change significantly.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Projection may preserve:

    * local structure
    * global structure

but rarely preserves everything perfectly.

In [5]:
vector_a = torch.tensor([
    1.0, 2.0, 3.0, 4.0
])

vector_b = torch.tensor([
    1.5, 2.5, 3.5, 10.0
])

high_dim_distance = torch.norm(
    vector_a - vector_b
)

projected_a = vector_a[:2]
projected_b = vector_b[:2]

low_dim_distance = torch.norm(
    projected_a - projected_b
)

print("\nOriginal High-Dimensional Distance:")
print(high_dim_distance)

print("\nProjected Low-Dimensional Distance:")
print(low_dim_distance)


Original High-Dimensional Distance:
tensor(6.0622)

Projected Low-Dimensional Distance:
tensor(0.7071)


Observe:

Projected distance became much smaller.

Why?

Because projection removed dimensions containing
large differences.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Projection may hide important structure.

# ============================================================
# SECTION 5 — DIMENSIONALITY REDUCTION INTUITION
# ============================================================

Dimensionality reduction attempts to preserve:

        important structure

while reducing dimensional complexity.

------------------------------------------------------------
# Common Goals
------------------------------------------------------------

Dimensionality reduction may attempt to preserve:

    * distances
    * neighborhoods
    * clusters
    * variance
    * topology

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Different projection methods preserve
different kinds of structure.

In [6]:
embeddings = torch.randn(10, 16)

print("\nOriginal Embedding Shape:")
print(embeddings.shape)

reduced_embeddings = embeddings[:, :2]

print("\nReduced Embedding Shape:")
print(reduced_embeddings.shape)


Original Embedding Shape:
torch.Size([10, 16])

Reduced Embedding Shape:
torch.Size([10, 2])


Shape transition:

            (10, 16)
                    ↓
             (10, 2)

means:

    16-dimensional geometry
            ↓
       2D projection

------------------------------------------------------------
# Important Clarification
------------------------------------------------------------

This is a simplified educational example.

Real methods include:

    * PCA
    * t-SNE
    * UMAP
    * autoencoders
Which we will cover later.

# ============================================================
# SECTION 6 — PROJECTION MATRICES
# ============================================================

Projection can also be represented mathematically
using matrices.

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

Suppose:

            x ∈ R^n

Projection matrix:

            P ∈ R^(m × n)

Projected vector:

                y = Px

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Projection becomes:

        structured geometric transformation

In [7]:
vector = torch.tensor([
    3.0,
    2.0,
    1.0
])

projection_matrix = torch.tensor([
    [1.0, 0.0, 0.0],
    [0.0, 1.0, 0.0]
])

projected = projection_matrix @ vector

print("\nOriginal Vector:\n")
print(vector)

print("\nProjection Matrix:\n")
print(projection_matrix)

print("\nProjected Vector:\n")
print(projected)


Original Vector:

tensor([3., 2., 1.])

Projection Matrix:

tensor([[1., 0., 0.],
        [0., 1., 0.]])

Projected Vector:

tensor([3., 2.])


Observe:

Matrix multiplication performed the projection.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Projection is fundamentally:

        coordinate transformation

inside geometric space.

# ============================================================
# SECTION 7 — LATENT STRUCTURE INTUITION
# ============================================================

Many high-dimensional systems contain hidden structure.

Projection sometimes reveals:

    * clusters
    * neighborhoods
    * manifolds
    * semantic organization

------------------------------------------------------------
# Important Idea
------------------------------------------------------------

High-dimensional representations are often NOT random.

They contain:

        structured organization

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Projection helps humans observe:

        hidden relational geometry

In [8]:
cluster_1 = torch.randn(5, 4) + 5
cluster_2 = torch.randn(5, 4) - 5

combined = torch.cat([
    cluster_1,
    cluster_2
], dim=0)

projected_clusters = combined[:, :2]

print("\nProjected Cluster Coordinates:\n")
print(projected_clusters)


Projected Cluster Coordinates:

tensor([[ 6.3032,  5.4879],
        [ 4.0173,  5.3018],
        [ 4.0709,  5.2762],
        [ 5.6333,  5.4050],
        [ 6.2554,  4.2850],
        [-4.3573, -4.4258],
        [-6.3793, -4.3742],
        [-5.1222, -5.7470],
        [-3.8070, -3.0627],
        [-4.5854, -3.8434]])


Observe:

Even after projection:

    local grouping structure may survive.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Projection can expose hidden organization
inside representation systems.

# ============================================================
# SECTION 8 — REPRESENTATION GEOMETRY
# ============================================================

One of the deepest ideas in representation learning:

High-dimensional systems may contain:

        meaningful geometric organization

Projection gives humans partial access to
that hidden structure.

------------------------------------------------------------
# Representation Flow
------------------------------------------------------------

            Raw Data
                ↓
        High-Dimensional Representation
                ↓
        Projection / Compression
                ↓
         Observable Structure
                ↓
        Human Interpretation

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Projection does NOT create structure.

It reveals approximations of existing structure.

In [9]:
print("\nProjection Pipeline:\n")

print("High-Dimensional Geometry")
print("            ↓")
print("Projection System")
print("            ↓")
print("Lower-Dimensional View")
print("            ↓")
print("Observable Structure")


Projection Pipeline:

High-Dimensional Geometry
            ↓
Projection System
            ↓
Lower-Dimensional View
            ↓
Observable Structure


# ============================================================
# FINAL SUMMARY
# ============================================================

# Key Ideas Learned

1. AI systems operate in high-dimensional spaces

2. Projection creates lower-dimensional views

3. Projection compresses information

4. Dimensionality reduction simplifies geometry

5. Projection may distort relationships

6. Projection matrices perform coordinate transformation

7. Hidden structure may exist inside representation spaces

------------------------------------------------------------
# Most Important Insight
------------------------------------------------------------

Visualization is NOT the original structure.

Projection provides:

        partial observable views

of high-dimensional representation geometry.

------------------------------------------------------------
# Connection to Future Topics
------------------------------------------------------------

This becomes foundational for:

    * latent spaces
    * semantic geometry
    * manifold learning
    * autoencoders
    * transformers
    * representation learning