# ============================================================
# STEP 02 — Embeddings as Geometric Coordinates
# ============================================================

# Core Idea

Embeddings place entities inside relational geometry.

An embedding transforms an entity into:

        a coordinate vector

inside a structured representation space.

------------------------------------------------------------
# Why Embedding is Required?
------------------------------------------------------------

Embeddings are NOT magical containers of meaning.

They are:

        learned coordinate systems

where relationships become geometrically measurable.

------------------------------------------------------------
# Mathematical Formulation
------------------------------------------------------------

An embedding function:

                    f(x)

maps an entity:

                    x

into a vector space:

                f(x) ∈ R^n

where:

    R^n = n-dimensional coordinate space


------------------------------------------------------------
# Example
------------------------------------------------------------

Suppose we observe the word:

                    "cat"

inside different sentences:

1. Two cats are fighting.
2. It's raining cats and dogs.
3. Pussy cat pussy cat where have you been.

------------------------------------------------------------
# Contextual Relationship Idea
------------------------------------------------------------

Words appear near other words.

These surrounding words create:

        contextual interaction patterns

For example:

    "cat" may frequently appear near:

        * animal-related words
        * household terms
        * action words
        * emotional expressions

------------------------------------------------------------
# Simplified Representation Idea
------------------------------------------------------------

Imagine we build a coordinate vector using
relationship strengths with nearby words:

        v(cat) = [
                    relation(two),
                    relation(raining),
                    relation(pussy),
                    relation(dog),
                    ...
                 ]

where:

    relation(word)

represents some measurable interaction strength.

------------------------------------------------------------
# Important Clarification-Be Cautious
------------------------------------------------------------

Real embeddings are NOT manually written
like this.

Instead:

    learning algorithms gradually organize
    words into geometric positions based on
    massive contextual interaction patterns.

------------------------------------------------------------
# Core Insight
------------------------------------------------------------

Words with similar contextual behavior
often become geometrically nearby.

This is one of the foundations of:

    * word embeddings
    * semantic geometry
    * representation learning
    * language models


------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Embeddings encode relationships through geometry.

Nearby embeddings:
        more similar relationships

Distant embeddings:
        more different relationships

------------------------------------------------------------
# Learning Goals
------------------------------------------------------------

By the end of this file you should understand:

    * embeddings as coordinates
    * learned representation spaces
    * geometric similarity
    * relational positioning
    * embedding tensors
    * local structure in vector spaces

------------------------------------------------------------

In [1]:
import torch

torch.manual_seed(42)

# ============================================================
# SECTION 1 — EMBEDDINGS AS COORDINATE VECTORS
# ============================================================

An embedding is simply:

            a vector representation

of an entity.

------------------------------------------------------------
# Mathematical Representation
------------------------------------------------------------

Embedding vector:

            e = [e1, e2, e3, ..., en]

where:

    ei = coordinate value
         along embedding dimension i

------------------------------------------------------------
# Important Clarification
------------------------------------------------------------

Embedding dimensions usually do NOT have
direct human interpretation.

Instead:

    the full geometry matters.

In [2]:
cat_embedding = torch.tensor([
    0.12,
    -0.84,
    0.33,
    0.91
])

dog_embedding = torch.tensor([
    0.15,
    -0.79,
    0.29,
    0.88
])

car_embedding = torch.tensor([
    -0.92,
    0.77,
    -0.44,
    -0.81
])

print("\nCat Embedding:\n")
print(cat_embedding)

print("\nDog Embedding:\n")
print(dog_embedding)

print("\nCar Embedding:\n")
print(car_embedding)


Cat Embedding:

tensor([ 0.1200, -0.8400,  0.3300,  0.9100])

Dog Embedding:

tensor([ 0.1500, -0.7900,  0.2900,  0.8800])

Car Embedding:

tensor([-0.9200,  0.7700, -0.4400, -0.8100])


Observe:

Each entity becomes:

            coordinates in space

This creates:

        representation geometry

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

The embedding itself is NOT semantic meaning.

Instead:

    meaning emerges from
    relationships between embeddings.
## How? We will understand gradually.

# ============================================================
# SECTION 2 — EMBEDDING SPACE GEOMETRY
# ============================================================

Embeddings create geometric organization.

------------------------------------------------------------
# Euclidean Distance
------------------------------------------------------------

Distance between embeddings:

                d(a,b) = ||a - b||

Expanded:

        d(a,b) = sqrt(
                            Σ(ai - bi)^2
                        )

------------------------------------------------------------
# Geometric Interpretation
------------------------------------------------------------

Small distance:
        nearby representations

Large distance:
        distant representations

------------------------------------------------------------
# Key Insight
------------------------------------------------------------

Similarity becomes measurable geometry.

In [3]:
cat_dog_distance = torch.norm(
    cat_embedding - dog_embedding
)

cat_car_distance = torch.norm(
    cat_embedding - car_embedding
)

print("\nDistance Between Cat and Dog:")
print(cat_dog_distance)

print("\nDistance Between Cat and Car:")
print(cat_car_distance)


Distance Between Cat and Dog:
tensor(0.0768)

Distance Between Cat and Car:
tensor(2.6879)


Observe:

Cat and Dog embeddings are closer.

This suggests:

    relational similarity

------------------------------------------------------------
# Important Clarification
------------------------------------------------------------

The system is NOT explicitly told:

        "cats and dogs are similar"

Instead:

    learning gradually organizes
    geometry relationally.

# ============================================================
# SECTION 3 — EMBEDDING MATRICES
# ============================================================

Real AI systems store MANY embeddings together.

------------------------------------------------------------
# Mathematical Representation
------------------------------------------------------------

Embedding matrix:

                    E ∈ R^(N × D)

where:

    N = number of entities
    D = embedding dimension

------------------------------------------------------------
# Tensor Interpretation
------------------------------------------------------------

Rows:
        entity embeddings

Columns:
        embedding dimensions

In [4]:
embedding_matrix = torch.tensor([
    [0.12, -0.84, 0.33, 0.91],   # Cat
    [0.15, -0.79, 0.29, 0.88],   # Dog
    [-0.92, 0.77, -0.44, -0.81], # Car
    [-0.88, 0.71, -0.39, -0.75], # Truck
])

entity_names = [
    "Cat",
    "Dog",
    "Car",
    "Truck"
]

print("\nEmbedding Matrix:\n")
print(embedding_matrix)

print("\nTensor Shape:")
print(embedding_matrix.shape)


Embedding Matrix:

tensor([[ 0.1200, -0.8400,  0.3300,  0.9100],
        [ 0.1500, -0.7900,  0.2900,  0.8800],
        [-0.9200,  0.7700, -0.4400, -0.8100],
        [-0.8800,  0.7100, -0.3900, -0.7500]])

Tensor Shape:
torch.Size([4, 4])


Tensor shape:

                (4, 4)

means:

    4 entities
    4-dimensional embedding space

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Large AI systems may use:

    * 128 dimensions
    * 512 dimensions
    * 768 dimensions
    * thousands of dimensions

High-dimensional geometry becomes the foundation
of representation learning.

## Representation Learning

Representation learning is the process where
an AI system automatically learns useful ways
to describe data.

Instead of humans manually defining features like:

    * edges in images
    * grammar rules in language
    * patterns in signals

the system gradually learns its own internal
representations from data.

------------------------------------------------------------
# Simple Intuition
------------------------------------------------------------

Raw data is often difficult to use directly.

Representation learning transforms:

        raw data
            ↓
    structured representations
            ↓
    useful relationships
            ↓
        task performance

------------------------------------------------------------
# Example
------------------------------------------------------------

An image initially contains:

    raw pixel values

A deep network gradually learns representations like:

    edges
        ↓
    textures
        ↓
    shapes
        ↓
    object structure

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Representation learning is fundamentally about:

    discovering useful structure inside data

# ============================================================
# SECTION 4 — RELATIONAL GEOMETRY
# ============================================================

Now we measure pairwise distances.

------------------------------------------------------------
# Core Philosophy
------------------------------------------------------------

Embeddings organize entities relationally.

This means:

    geometry stores structure.

------------------------------------------------------------
# Important Idea
------------------------------------------------------------

Embedding systems create:

        similarity neighborhoods

In [5]:
print("\nPairwise Embedding Distances:\n")

for i in range(len(embedding_matrix)):

    for j in range(i + 1, len(embedding_matrix)):

        distance = torch.norm(
            embedding_matrix[i]
            - embedding_matrix[j]
        )

        print(
            f"{entity_names[i]} <-> "
            f"{entity_names[j]}"
            f" : {distance:.4f}"
        )


Pairwise Embedding Distances:

Cat <-> Dog : 0.0768
Cat <-> Car : 2.6879
Cat <-> Truck : 2.5839
Dog <-> Car : 2.6396
Dog <-> Truck : 2.5358
Car <-> Truck : 0.1063


Observe:

    Cat ↔ Dog
    Car ↔ Truck

form local geometric neighborhoods.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Embedding spaces naturally organize:

    related entities nearby

This becomes the basis for:

    * semantic search
    * recommendation systems
    * retrieval systems
    * language models

# ============================================================
# SECTION 5 — HOW LEARNING EMERGE IN EMBEDDINGS 
# ============================================================

One of the most important ideas in representation learning:

Embeddings are LEARNED.

------------------------------------------------------------
# Mathematical Idea
------------------------------------------------------------

Training gradually adjusts coordinates:

                E_new = E_old + ΔE

where:

    ΔE = learned coordinate update

------------------------------------------------------------
# Core Principle
------------------------------------------------------------

Learning reshapes geometry.

This creates:

    structured representation spaces.

In [6]:
random_embeddings = torch.randn(5, 6)

print("\nRandom Initial Embeddings:\n")
print(random_embeddings)


Random Initial Embeddings:

tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345],
        [-0.0431, -1.6047, -0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -2.3169, -0.2168, -1.3847, -0.8712],
        [-0.2234,  1.7174,  0.3189, -0.4245, -0.8286,  0.3309],
        [-1.5576,  0.9956, -0.8798, -0.6011, -1.2742,  2.1228]])


Initially:

    embeddings may contain random geometry.

During training:

    geometry reorganizes itself.

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Learning often becomes:

        geometric restructuring

inside representation space.

# ============================================================
# SECTION 6 — LOCAL STRUCTURE IN EMBEDDING SPACES
# ============================================================

Embedding systems create local neighborhoods.

------------------------------------------------------------
# Neighborhood Idea
------------------------------------------------------------

Nearby vectors often share:

    * properties
    * behaviors
    * semantic structure
    * interaction patterns

------------------------------------------------------------
# Important Concept
------------------------------------------------------------

Local geometry becomes meaningful structure.

In [7]:
query_embedding = cat_embedding

print("\nQuery Embedding (Cat):\n")
print(query_embedding)

print("\nDistances From Query:\n")

for i, entity in enumerate(entity_names):

    distance = torch.norm(
        query_embedding
        - embedding_matrix[i]
    )

    print(f"Cat <-> {entity} : {distance:.4f}")


Query Embedding (Cat):

tensor([ 0.1200, -0.8400,  0.3300,  0.9100])

Distances From Query:

Cat <-> Cat : 0.0000
Cat <-> Dog : 0.0768
Cat <-> Car : 2.6879
Cat <-> Truck : 2.5839


Observe:

Closest entities become nearest neighbors.

This idea becomes fundamental for:

    * vector databases
    * retrieval systems
    * recommendation engines
    * semantic search

------------------------------------------------------------
# Important Insight
------------------------------------------------------------

Many AI systems operate through:

        nearest-neighbor geometry

# ============================================================
# SECTION 7 — EMBEDDINGS AS REPRESENTATION SYSTEMS
# ============================================================

Embeddings are more than vectors.

They create:

        navigable relational spaces

------------------------------------------------------------
# Representation Pipeline
------------------------------------------------------------

                Entity
                    ↓
            Embedding Function
                    ↓
            Coordinate Vector
                    ↓
           Geometric Structure
                    ↓
          Relational Organization

------------------------------------------------------------
# Extremely Important Insight
------------------------------------------------------------

Modern AI systems frequently operate by:

        transforming geometry

rather than manipulating symbolic meaning directly.

In [8]:
print("\nEmbedding Representation Pipeline:\n")

print("Entity")
print("   ↓")
print("Embedding Function")
print("   ↓")
print("Coordinate Vector")
print("   ↓")
print("Geometric Relationships")
print("   ↓")
print("Representation Structure")


Embedding Representation Pipeline:

Entity
   ↓
Embedding Function
   ↓
Coordinate Vector
   ↓
Geometric Relationships
   ↓
Representation Structure


# ============================================================
# FINAL SUMMARY
# ============================================================

# Key Ideas Learned

1. Embeddings are coordinate vectors

2. Embedding spaces organize relationships

3. Similarity becomes measurable geometry

4. Embedding matrices store many representations

5. Learning reshapes geometric structure

6. Local neighborhoods encode relational similarity

7. Modern AI systems frequently manipulate geometry

------------------------------------------------------------
# Most Important Insight
------------------------------------------------------------

Embeddings transform entities into:

            navigable geometric coordinates

inside representation spaces.

Meaning emerges from:

        relational positioning

rather than isolated symbolic definitions.

------------------------------------------------------------
# Connection to Future Topics
------------------------------------------------------------

This becomes the foundation for:

    * latent spaces
    * transformers
    * semantic search
    * vector databases
    * representation learning
    * multimodal systems