# STEP 04 — BOOLEAN MASKING

## CORE INTUITION

Boolean masking controls information flow.

A mask determines:

- what becomes visible
- what becomes hidden
- what participates in computation
- what gets ignored

Masking is one of the most important ideas
in modern tensor systems.

It appears constantly in:

- transformers
- attention systems
- NLP
- segmentation
- anomaly filtering
- reinforcement learning

This step introduces:

- boolean tensors
- conditional tensor selection
- logical masking
- masked computation
- information filtering systems

In [1]:


# ============================================================
# IMPORTS
# ============================================================

import torch

# ============================================================
# GLOSSARY
# ============================================================

## Boolean Tensor

A boolean tensor contains:

    True
    False

values.


------------------------------------------------------------

## Mask

A mask is a logical tensor controlling
tensor visibility.


------------------------------------------------------------

## Boolean Indexing

Boolean indexing selects tensor elements
where the mask equals:

    True


------------------------------------------------------------

## Conditional Selection

Masks enable conditional tensor computation.


------------------------------------------------------------

## Information Filtering

Masking filters relevant tensor regions
while ignoring others.


------------------------------------------------------------

## Sparse Visibility

Masks allow partial tensor visibility
without modifying original tensor structure.

# ============================================================
# SECTION 01 — BASIC BOOLEAN MASKING
# ============================================================

A logical condition creates a boolean mask.

In [2]:


# ============================================================
# BASIC BOOLEAN MASKING
# ============================================================

tensor = torch.tensor(
    [5, 12, 7, 20, 3, 15]
)

print("\n" + "=" * 80)
print("BASIC BOOLEAN MASKING")
print("=" * 80)

print(f"\nOriginal Tensor:\n{tensor}")

mask = tensor > 10

print(f"\nBoolean Mask:\n{mask}")

filtered_tensor = tensor[mask]

print(f"\nFiltered Tensor:\n{filtered_tensor}")


BASIC BOOLEAN MASKING

Original Tensor:
tensor([ 5, 12,  7, 20,  3, 15])

Boolean Mask:
tensor([False,  True, False,  True, False,  True])

Filtered Tensor:
tensor([12, 20, 15])


# MASK GEOMETRY

tensor > 10

creates:

    [False, True, False, True, False, True]

Only positions where:

    mask == True

become visible.

# ============================================================
# SECTION 02 — BOOLEAN INDEXING
# ============================================================

Masks can directly index tensors.

In [3]:


# ============================================================
# BOOLEAN INDEXING
# ============================================================

tensor = torch.tensor(
    [2, 4, 6, 8, 10]
)

mask = torch.tensor(
    [True, False, True, False, True]
)

print("\n" + "=" * 80)
print("BOOLEAN INDEXING")
print("=" * 80)

print(f"\nTensor:\n{tensor}")

print(f"\nMask:\n{mask}")

result = tensor[mask]

print(f"\nSelected Elements:\n{result}")


BOOLEAN INDEXING

Tensor:
tensor([ 2,  4,  6,  8, 10])

Mask:
tensor([ True, False,  True, False,  True])

Selected Elements:
tensor([ 2,  6, 10])


# GEOMETRIC INTERPRETATION

The mask behaves like a visibility filter.

Visible positions:

    True

Hidden positions:

    False

# ============================================================
# SECTION 03 — CONDITIONAL FILTERING
# ============================================================

Logical conditions dynamically create masks.

In [4]:


# ============================================================
# CONDITIONAL FILTERING
# ============================================================

tensor = torch.randn(10)

print("\n" + "=" * 80)
print("CONDITIONAL FILTERING")
print("=" * 80)

print(f"\nOriginal Tensor:\n{tensor}")

positive_mask = tensor > 0

positive_values = tensor[positive_mask]

print(f"\nPositive Mask:\n{positive_mask}")

print(f"\nPositive Values:\n{positive_values}")


CONDITIONAL FILTERING

Original Tensor:
tensor([-0.1513,  0.1482, -0.4205, -0.4183,  0.2987,  1.4047, -0.5724, -1.1316,
        -0.9095, -1.0192])

Positive Mask:
tensor([False,  True, False, False,  True,  True, False, False, False, False])

Positive Values:
tensor([0.1482, 0.2987, 1.4047])


# MATHEMATICAL FORMULATION

Mask:

    M[i] = True
    if
    Tensor[i] > 0

Selection:

    Output = Tensor[M]

# ============================================================
# SECTION 04 — MASKING MULTI-DIMENSIONAL TENSORS
# ============================================================

Masking also works on higher-dimensional tensors.

In [5]:


# ============================================================
# MULTI-DIMENSIONAL MASKING
# ============================================================

tensor = torch.tensor(
    [
        [5, 12, 7],
        [20, 3, 15]
    ]
)

print("\n" + "=" * 80)
print("MULTI-DIMENSIONAL MASKING")
print("=" * 80)

print(f"\nOriginal Tensor:\n{tensor}")

mask = tensor > 10

print(f"\nMask:\n{mask}")

filtered_values = tensor[mask]

print(f"\nFiltered Values:\n{filtered_values}")


MULTI-DIMENSIONAL MASKING

Original Tensor:
tensor([[ 5, 12,  7],
        [20,  3, 15]])

Mask:
tensor([[False,  True, False],
        [ True, False,  True]])

Filtered Values:
tensor([12, 20, 15])


# GEOMETRIC OBSERVATION

The mask preserves tensor geometry.

Selection extracts values corresponding
to True positions.

# ============================================================
# SECTION 05 — MASKED ASSIGNMENT
# ============================================================

Masks can modify tensor regions selectively.

In [6]:


# ============================================================
# MASKED ASSIGNMENT
# ============================================================

tensor = torch.tensor(
    [1, 5, 10, 15, 20]
)

print("\n" + "=" * 80)
print("MASKED ASSIGNMENT")
print("=" * 80)

print(f"\nOriginal Tensor:\n{tensor}")

mask = tensor > 10

tensor[mask] = -1

print(f"\nModified Tensor:\n{tensor}")


MASKED ASSIGNMENT

Original Tensor:
tensor([ 1,  5, 10, 15, 20])

Modified Tensor:
tensor([ 1,  5, 10, -1, -1])


# MASKED COMPUTATION

Only positions satisfying the logical condition
were modified.

# ============================================================
# SECTION 06 — torch.where()
# ============================================================

torch.where() performs conditional selection.

In [12]:


# ============================================================
# TORCH WHERE
# ============================================================

tensor = torch.tensor(
    [5, 12, 7, 20]
)

print("\n" + "=" * 80)
print("TORCH WHERE")
print("=" * 80)

print(f"\nOriginal Tensor:\n{tensor}")

result = torch.where(
    tensor > 10,
    torch.tensor(1),
    torch.tensor(0)
)

print(f"\nResult:\n{result}")


TORCH WHERE

Original Tensor:
tensor([ 5, 12,  7, 20])

Result:
tensor([20, 11, 20, 11])


# MATHEMATICAL INTERPRETATION

For each tensor element:

    if condition == True:
        output = value_a

    else:
        output = value_b

# ============================================================
# SECTION 07 — COMBINING MASKS
# ============================================================

Logical operations can combine masks.

In [8]:


# ============================================================
# COMBINING MASKS
# ============================================================

tensor = torch.tensor(
    [5, 12, 18, 25, 30]
)

print("\n" + "=" * 80)
print("COMBINING MASKS")
print("=" * 80)

print(f"\nOriginal Tensor:\n{tensor}")

mask_1 = tensor > 10

mask_2 = tensor < 25

combined_mask = mask_1 & mask_2

print(f"\nMask 1:\n{mask_1}")

print(f"\nMask 2:\n{mask_2}")

print(f"\nCombined Mask:\n{combined_mask}")

result = tensor[combined_mask]

print(f"\nFiltered Result:\n{result}")


COMBINING MASKS

Original Tensor:
tensor([ 5, 12, 18, 25, 30])

Mask 1:
tensor([False,  True,  True,  True,  True])

Mask 2:
tensor([ True,  True,  True, False, False])

Combined Mask:
tensor([False,  True,  True, False, False])

Filtered Result:
tensor([12, 18])


# LOGICAL GEOMETRY

AND operation:

    condition_1 AND condition_2

Only elements satisfying both conditions
remain visible.

# ============================================================
# SECTION 08 — MASKING IMAGE TENSORS
# ============================================================

Masking becomes extremely important in
computer vision systems.

In [9]:


# ============================================================
# IMAGE-LIKE TENSOR
# ============================================================

image_tensor = torch.randn(
    3, 4, 4
)

print("\n" + "=" * 80)
print("IMAGE TENSOR MASKING")
print("=" * 80)

print(
    f"\nImage Tensor Shape:\n"
    f"{image_tensor.shape}"
)

high_intensity_mask = image_tensor > 0.5

high_values = image_tensor[
    high_intensity_mask
]

print(
    f"\nNumber of High Intensity Values:\n"
    f"{high_values.numel()}"
)


IMAGE TENSOR MASKING

Image Tensor Shape:
torch.Size([3, 4, 4])

Number of High Intensity Values:
13


# COMPUTER VISION CONNECTION

Masks can isolate:

- edges
- objects
- regions
- activations
- segmentation zones

# ============================================================
# SECTION 09 — ATTENTION MASK INTUITION
# ============================================================

Transformers use masks extensively.

Example:

- hide future tokens
- ignore padding
- control attention visibility

In [10]:


# ============================================================
# SIMPLE ATTENTION MASK
# ============================================================

attention_scores = torch.tensor(
    [
        [1.2, 0.8, 0.5],
        [0.7, 1.5, 0.3],
        [0.2, 0.4, 1.8]
    ]
)

mask = torch.tensor(
    [
        [True, True, False],
        [True, True, False],
        [True, True, False]
    ]
)

print("\n" + "=" * 80)
print("ATTENTION MASK INTUITION")
print("=" * 80)

print(f"\nAttention Scores:\n{attention_scores}")

print(f"\nMask:\n{mask}")

masked_scores = attention_scores.masked_fill(
    ~mask,
    float("-inf")
)

print(f"\nMasked Scores:\n{masked_scores}")


ATTENTION MASK INTUITION

Attention Scores:
tensor([[1.2000, 0.8000, 0.5000],
        [0.7000, 1.5000, 0.3000],
        [0.2000, 0.4000, 1.8000]])

Mask:
tensor([[ True,  True, False],
        [ True,  True, False],
        [ True,  True, False]])

Masked Scores:
tensor([[1.2000, 0.8000,   -inf],
        [0.7000, 1.5000,   -inf],
        [0.2000, 0.4000,   -inf]])


# ATTENTION INTUITION

Masked positions become inaccessible.

The mask controls:

    information visibility

inside the attention system.

# ============================================================
# SECTION 10 — MEMORY AND MASKING
# ============================================================

Masks themselves are tensors.

Large-scale masking systems may consume
significant memory.

In [11]:


# ============================================================
# MEMORY INFORMATION
# ============================================================

tensor = torch.randn(1000)

mask = tensor > 0

print("\n" + "=" * 80)
print("MEMORY INFORMATION")
print("=" * 80)

print(f"\nTensor Shape : {tensor.shape}")

print(f"Mask Shape   : {mask.shape}")

print(
    f"\nTensor Memory : "
    f"{tensor.numel() * tensor.element_size()} Bytes"
)

print(
    f"Mask Memory   : "
    f"{mask.numel() * mask.element_size()} Bytes"
)


MEMORY INFORMATION

Tensor Shape : torch.Size([1000])
Mask Shape   : torch.Size([1000])

Tensor Memory : 4000 Bytes
Mask Memory   : 1000 Bytes


# MEMORY OBSERVATION

Boolean tensors also occupy memory.

Large attention masks can become computationally
expensive in transformer systems.

# ============================================================
# IMPORTANT DEEP LEARNING CONNECTIONS
# ============================================================

Boolean masking appears constantly in:

- transformers
- attention systems
- NLP
- segmentation
- anomaly detection
- sparse computation
- reinforcement learning
- token filtering
- recommendation systems

Understanding masking deeply is foundational
for modern AI systems.

# ============================================================
# FINAL CONCEPTUAL SUMMARY
# ============================================================

Boolean masking controls tensor visibility.

It enables:

- selective computation
- conditional routing
- sparse interaction
- information filtering

Masking is not merely:

    conditional selection

It is:

    structured information flow control
    inside tensor systems.