# STEP 05 — GATHER AND SCATTER

## CORE INTUITION

Gather and scatter are tensor routing operations.

They allow tensor systems to:

- collect information
- redistribute information
- dynamically route values
- reorganize tensor structure

Core idea:

    tensors can move information selectively

This becomes extremely important in:

- attention systems
- transformers
- graph neural networks
- sparse computation
- recommendation systems
- reinforcement learning

This step introduces:

- gather()
- scatter()
- index-based routing
- tensor information flow
- dynamic tensor interaction

In [1]:


# ============================================================
# IMPORTS
# ============================================================

import torch

# ============================================================
# GLOSSARY
# ============================================================

## Gather

gather() extracts tensor values
using index tensors.


------------------------------------------------------------

## Scatter

scatter() writes tensor values
into selected tensor locations.


------------------------------------------------------------

## Index Tensor

An index tensor specifies:

    where information should move.


------------------------------------------------------------

## Tensor Routing

Gather and scatter enable dynamic
information routing inside tensor systems.


------------------------------------------------------------

## Sparse Interaction

These operations allow selective computation
without processing entire tensors.

# ============================================================
# SECTION 01 — BASIC GATHER
# ============================================================

gather() extracts tensor values
from specified index positions.

In [2]:


# ============================================================
# BASIC GATHER
# ============================================================

tensor = torch.tensor(
    [
        [10, 20, 30],
        [40, 50, 60]
    ]
)

index_tensor = torch.tensor(
    [
        [0, 2],
        [1, 0]
    ]
)

print("\n" + "=" * 80)
print("BASIC GATHER")
print("=" * 80)

print(f"\nOriginal Tensor:\n{tensor}")

print(f"\nIndex Tensor:\n{index_tensor}")

result = torch.gather(
    tensor,
    dim=1,
    index=index_tensor
)

print(f"\nGather Result:\n{result}")


BASIC GATHER

Original Tensor:
tensor([[10, 20, 30],
        [40, 50, 60]])

Index Tensor:
tensor([[0, 2],
        [1, 0]])

Gather Result:
tensor([[10, 30],
        [50, 40]])


# GATHER GEOMETRY

dim=1 means:

    gather across columns

Selections:

    tensor[0,0] -> 10
    tensor[0,2] -> 30

    tensor[1,1] -> 50
    tensor[1,0] -> 40

# ============================================================
# SECTION 02 — GATHER ALONG ROWS
# ============================================================

Gathering can occur across different dimensions.

In [3]:


# ============================================================
# ROW-WISE GATHER
# ============================================================

tensor = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

index_tensor = torch.tensor(
    [
        [0, 1, 2],
        [2, 1, 0]
    ]
)

print("\n" + "=" * 80)
print("ROW-WISE GATHER")
print("=" * 80)

print(f"\nOriginal Tensor:\n{tensor}")

print(f"\nIndex Tensor:\n{index_tensor}")

result = torch.gather(
    tensor,
    dim=0,
    index=index_tensor
)

print(f"\nGather Result:\n{result}")


ROW-WISE GATHER

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Index Tensor:
tensor([[0, 1, 2],
        [2, 1, 0]])

Gather Result:
tensor([[1, 5, 9],
        [7, 5, 3]])


# DIMENSIONAL INTERPRETATION

dim=0 means:

    gather across rows

The index tensor specifies:

    which row to extract from

# ============================================================
# SECTION 03 — GATHER AND PROBABILITY SELECTION
# ============================================================

Gather is heavily used in classification systems.

In [4]:


# ============================================================
# CLASS PROBABILITY SELECTION
# ============================================================

probabilities = torch.tensor(
    [
        [0.1, 0.7, 0.2],
        [0.8, 0.1, 0.1],
        [0.2, 0.3, 0.5]
    ]
)

target_classes = torch.tensor(
    [
        [1],
        [0],
        [2]
    ]
)

print("\n" + "=" * 80)
print("CLASS PROBABILITY GATHER")
print("=" * 80)

print(f"\nProbabilities:\n{probabilities}")

print(f"\nTarget Classes:\n{target_classes}")

selected_probabilities = torch.gather(
    probabilities,
    dim=1,
    index=target_classes
)

print(
    f"\nSelected Probabilities:\n"
    f"{selected_probabilities}"
)


CLASS PROBABILITY GATHER

Probabilities:
tensor([[0.1000, 0.7000, 0.2000],
        [0.8000, 0.1000, 0.1000],
        [0.2000, 0.3000, 0.5000]])

Target Classes:
tensor([[1],
        [0],
        [2]])

Selected Probabilities:
tensor([[0.7000],
        [0.8000],
        [0.5000]])


# DEEP LEARNING CONNECTION

Cross entropy systems often gather:

    correct class probabilities

using target labels as index tensors.

# ============================================================
# SECTION 04 — BASIC SCATTER
# ============================================================

scatter() writes values into selected positions.

In [5]:


# ============================================================
# BASIC SCATTER
# ============================================================

base_tensor = torch.zeros(
    3, 5
)

index_tensor = torch.tensor(
    [
        [0, 2],
        [1, 3],
        [4, 0]
    ]
)

source_tensor = torch.tensor(
    [
        [10, 20],
        [30, 40],
        [50, 60]
    ]
).float()

print("\n" + "=" * 80)
print("BASIC SCATTER")
print("=" * 80)

print(f"\nBase Tensor:\n{base_tensor}")

print(f"\nIndex Tensor:\n{index_tensor}")

print(f"\nSource Tensor:\n{source_tensor}")

result = base_tensor.scatter(
    dim=1,
    index=index_tensor,
    src=source_tensor
)

print(f"\nScatter Result:\n{result}")


BASIC SCATTER

Base Tensor:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Index Tensor:
tensor([[0, 2],
        [1, 3],
        [4, 0]])

Source Tensor:
tensor([[10., 20.],
        [30., 40.],
        [50., 60.]])

Scatter Result:
tensor([[10.,  0., 20.,  0.,  0.],
        [ 0., 30.,  0., 40.,  0.],
        [60.,  0.,  0.,  0., 50.]])


# SCATTER GEOMETRY

scatter():

    routes source values into target positions

The index tensor determines:

    where information is written.

# ============================================================
# SECTION 05 — SCATTER WITH CONSTANT VALUES
# ============================================================

scatter() can also insert constant values.

In [6]:


# ============================================================
# CONSTANT VALUE SCATTER
# ============================================================

tensor = torch.zeros(3, 4)

index_tensor = torch.tensor(
    [
        [1],
        [2],
        [0]
    ]
)

print("\n" + "=" * 80)
print("CONSTANT VALUE SCATTER")
print("=" * 80)

print(f"\nOriginal Tensor:\n{tensor}")

result = tensor.scatter(
    dim=1,
    index=index_tensor,
    value=1
)

print(f"\nScatter Result:\n{result}")


CONSTANT VALUE SCATTER

Original Tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Scatter Result:
tensor([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]])


# GEOMETRIC INTERPRETATION

The value:

    1

is routed into indexed positions.

# ============================================================
# SECTION 06 — ONE-HOT ENCODING
# ============================================================

scatter() is commonly used to create
one-hot representations.

In [7]:


# ============================================================
# ONE-HOT ENCODING
# ============================================================

class_indices = torch.tensor(
    [
        [0],
        [2],
        [1]
    ]
)

num_classes = 4

one_hot = torch.zeros(
    class_indices.size(0),
    num_classes
)

print("\n" + "=" * 80)
print("ONE-HOT ENCODING")
print("=" * 80)

print(f"\nClass Indices:\n{class_indices}")

one_hot.scatter_(
    dim=1,
    index=class_indices,
    value=1
)

print(f"\nOne-Hot Tensor:\n{one_hot}")


ONE-HOT ENCODING

Class Indices:
tensor([[0],
        [2],
        [1]])

One-Hot Tensor:
tensor([[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.]])


# ONE-HOT GEOMETRY

Each row becomes:

    a sparse class representation

Only one position contains:

    1

# ============================================================
# SECTION 07 — HIGHER DIMENSION GATHER
# ============================================================

Gather also works on higher-dimensional tensors.

In [8]:


# ============================================================
# HIGHER DIMENSION GATHER
# ============================================================

tensor = torch.randn(
    2, 3, 4
)

index_tensor = torch.tensor(
    [
        [
            [0, 1],
            [2, 0],
            [1, 3]
        ],

        [
            [3, 2],
            [1, 0],
            [0, 2]
        ]
    ]
)

print("\n" + "=" * 80)
print("HIGHER DIMENSION GATHER")
print("=" * 80)

print(f"\nTensor Shape : {tensor.shape}")

print(f"Index Shape  : {index_tensor.shape}")

result = torch.gather(
    tensor,
    dim=2,
    index=index_tensor
)

print(f"\nResult Shape : {result.shape}")


HIGHER DIMENSION GATHER

Tensor Shape : torch.Size([2, 3, 4])
Index Shape  : torch.Size([2, 3, 2])

Result Shape : torch.Size([2, 3, 2])


# HIGHER DIMENSION INTERPRETATION

Gather operates independently across
specified dimensions.

This enables dynamic information extraction
inside complex tensor systems.

# ============================================================
# SECTION 08 — ATTENTION INTUITION
# ============================================================

Transformers heavily rely on tensor routing.

In [9]:


# ============================================================
# SIMPLE ATTENTION ROUTING
# ============================================================

attention_scores = torch.tensor(
    [
        [0.1, 0.8, 0.1],
        [0.6, 0.2, 0.2]
    ]
)

top_indices = torch.argmax(
    attention_scores,
    dim=1,
    keepdim=True
)

values = torch.tensor(
    [
        [100, 200, 300],
        [400, 500, 600]
    ]
)

print("\n" + "=" * 80)
print("ATTENTION ROUTING")
print("=" * 80)

print(f"\nAttention Scores:\n{attention_scores}")

print(f"\nTop Indices:\n{top_indices}")

selected_values = torch.gather(
    values,
    dim=1,
    index=top_indices
)

print(f"\nSelected Values:\n{selected_values}")


ATTENTION ROUTING

Attention Scores:
tensor([[0.1000, 0.8000, 0.1000],
        [0.6000, 0.2000, 0.2000]])

Top Indices:
tensor([[1],
        [0]])

Selected Values:
tensor([[200],
        [400]])


# ATTENTION CONNECTION

Attention systems dynamically gather:

    relevant information

based on learned interaction scores.

# ============================================================
# SECTION 09 — MEMORY AND ROUTING
# ============================================================

Gather and scatter manipulate tensor flow
without necessarily modifying original geometry.

In [10]:


# ============================================================
# MEMORY INFORMATION
# ============================================================

tensor = torch.randn(1000, 1000)

index_tensor = torch.randint(
    0,
    1000,
    (1000, 100)
)

print("\n" + "=" * 80)
print("MEMORY INFORMATION")
print("=" * 80)

print(
    f"\nTensor Memory : "
    f"{tensor.numel() * tensor.element_size()} Bytes"
)

print(
    f"Index Memory  : "
    f"{index_tensor.numel() * index_tensor.element_size()} Bytes"
)


MEMORY INFORMATION

Tensor Memory : 4000000 Bytes
Index Memory  : 800000 Bytes


# MEMORY OBSERVATION

Routing systems require index tensors.

Large-scale routing operations can become
memory intensive in advanced architectures.

# ============================================================
# IMPORTANT DEEP LEARNING CONNECTIONS
# ============================================================

Gather and scatter appear constantly in:

- transformers
- graph neural networks
- sparse systems
- recommendation systems
- reinforcement learning
- token routing
- mixture-of-experts systems
- attention architectures

Understanding tensor routing deeply is foundational
for modern AI systems.

# ============================================================
# FINAL CONCEPTUAL SUMMARY
# ============================================================

Gather and scatter enable dynamic tensor routing.

They allow tensor systems to:

- extract information
- redirect information
- build sparse interaction systems
- perform selective computation

Gather and scatter are not merely:

    indexing operations

They are:

    structured tensor information routing systems.