Step 01 — Tensor Broadcasting

Core intuition:

Dimensions negotiate compatibility.

Learn:

singleton dimensions
implicit expansion
broadcasting rules
shape alignment

This is foundational.

In [1]:
import torch

============================================================
TENSOR BROADCASTING — GLOSSARY
============================================================

This glossary introduces the major concepts,
tensor operations, and mathematical ideas used in:

    step_01_tensor_broadcasting.py

The goal is not only API familiarity.

The goal is to develop:

- tensor intuition
- dimensional reasoning
- broadcasting geometry understanding

============================================================
WHAT IS BROADCASTING?
============================================================

Broadcasting is PyTorch's mechanism for performing
operations between tensors with different shapes.

Instead of explicitly copying data,
PyTorch attempts to:

    align dimensions geometrically

before computation.

Example:

    tensor_1.shape = [3, 4]
    tensor_2.shape = [1, 4]

PyTorch implicitly expands:

    [1, 4]
        ↓
    [3, 4]

This process is called:

    broadcasting

In [2]:
print("="*80)
print("Tensor Broadcasting")
print("="*80)
x1 = torch.rand(3, 4)
y1 = torch.randn(1, 4)
print(f"x:\n {x1},\n y:\n {y1}")
# Observe how the shapes are different

Tensor Broadcasting
x:
 tensor([[0.9681, 0.7799, 0.3555, 0.8790],
        [0.1858, 0.9276, 0.5551, 0.5895],
        [0.2426, 0.8480, 0.2763, 0.3683]]),
 y:
 tensor([[-0.0784, -0.0686, -0.2174, -0.2527]])




============================================================
CORE BROADCASTING INTUITION
============================================================

Broadcasting is not random expansion.

It follows structural compatibility rules.

Core idea:

    Dimensions negotiate compatibility.

============================================================
IMPORTANT TENSOR CONCEPTS
============================================================

============================================================
TENSOR SHAPE
============================================================

The shape of a tensor describes
its dimensional structure.

Example:

    tensor.shape

Output:

    torch.Size([3, 4])

Meaning:

- 3 rows
- 4 columns

============================================================
DIMENSION
============================================================

A dimension is one axis of tensor structure.

Example:

    [Batch, Channels, Height, Width]

contains:

- Batch dimension
- Channel dimension
- Height dimension
- Width dimension

============================================================
SINGLETON DIMENSION
============================================================

A singleton dimension has size:

    1

Example:

    [1, 4]

Singleton dimensions are extremely important
because they can expand during broadcasting.

In [15]:
print("shape of x1:", x1.shape)
print("shape of y:", y1.shape)
print(f" add(x,y):\n {torch.add(x1,y1)})")
print("."*80)
x2 = torch.rand(3, 4)
y2 = torch.randn(2, 4)
print(f"x:\n {x1},\n y:\n {y1}")
print("shape of x2:", x2.shape)
print("shape of y2:", y2.shape)
try:
    print(f" add(x2,y2):\n {torch.add(x2,y2)})")
except Exception as e:
    print("." * 80)
    print(f" add(x2,y2): Error: {e}")
    print("." * 80)
    print('CAN YOU SEE WHY YOU CAN ADD x1 AND y1 BUT YOU CANNOT ADD x2 AND y2?')
    print("." * 80)
    pass

shape of x1: torch.Size([3, 4])
shape of y: torch.Size([1, 4])
 add(x,y):
 tensor([[0.8897, 0.7113, 0.1381, 0.6263],
        [0.1074, 0.8589, 0.3378, 0.3368],
        [0.1642, 0.7794, 0.0589, 0.1156]]))
................................................................................
x:
 tensor([[0.9681, 0.7799, 0.3555, 0.8790],
        [0.1858, 0.9276, 0.5551, 0.5895],
        [0.2426, 0.8480, 0.2763, 0.3683]]),
 y:
 tensor([[-0.0784, -0.0686, -0.2174, -0.2527]])
shape of x2: torch.Size([3, 4])
shape of y2: torch.Size([2, 4])
................................................................................
 add(x2,y2): Error: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0
................................................................................
CAN YOU SEE WHY YOU CAN ADD x1 AND y1 BUT YOU CANNOT ADD x2 AND y2?
................................................................................


============================================================
BROADCASTING RULES
============================================================

PyTorch compares tensor shapes:

    right to left

Two dimensions are compatible if:

1. They are equal

OR

2. One of them is:

    1

============================================================
EXAMPLE BROADCASTING
============================================================

Tensor A:

    [3, 4]

Tensor B:

    [1, 4]

Broadcasting result:

    [3, 4]

because:

    1 expands to 3

============================================================
TENSOR OPERATIONS USED
============================================================

============================================================
ADDITION
============================================================

torch.add()

or

+

Performs element-wise addition.

Example:

    a + b

============================================================
MULTIPLICATION
============================================================

torch.mul()

or

*

Performs element-wise multiplication.

============================================================
SHAPE INSPECTION
============================================================

tensor.shape

Returns tensor dimensions.

============================================================
DIMENSION EXPANSION
============================================================

tensor.unsqueeze()

Adds a new dimension.

Example:

    tensor.unsqueeze(0)

============================================================
DIMENSION REMOVAL
============================================================

tensor.squeeze()

Removes singleton dimensions.

============================================================
TENSOR RESHAPING
============================================================

tensor.reshape()

Changes tensor geometry
without changing data.

============================================================
TENSOR VIEWING
============================================================

tensor.view()

Creates a different tensor
perspective over memory.

============================================================
EXPLICIT EXPANSION
============================================================

tensor.expand()

Explicitly expands singleton dimensions
without copying memory.

Example:

    tensor.expand(3, 4)

============================================================
TENSOR REPETITION
============================================================

tensor.repeat()

Repeats tensor data physically in memory.

Unlike broadcasting:

    repeat() copies data
    expand() does not

============================================================
MATHEMATICAL CONCEPTS
============================================================

============================================================
ELEMENT-WISE OPERATIONS
============================================================

Operations are applied independently
to corresponding tensor elements.

Example:

    A[i, j] + B[i, j]

============================================================
SHAPE COMPATIBILITY
============================================================

Broadcasting requires compatible tensor geometry.

Mathematically:

    dimensions must align structurally

before operations can occur.

============================================================
IMPLICIT EXPANSION
============================================================

Broadcasting creates the illusion
of larger tensors without copying memory.

This is conceptually similar to:

    virtual geometric expansion

============================================================
TENSOR GEOMETRY
============================================================

Tensor shapes encode structural meaning.

Example:

    [Batch, Channels, Height, Width]

is not merely:

    four numbers

It represents:

- tensor population
- information fields
- spatial structure

============================================================
COMMON BROADCASTING PATTERNS
============================================================

============================================================
VECTOR + SCALAR
============================================================

[3] + [1]

Example:

    tensor + 5

The scalar broadcasts across all elements.

============================================================
MATRIX + VECTOR
============================================================

[3, 4] + [4]

The vector broadcasts across rows.

============================================================
BATCH BROADCASTING
============================================================

[32, 3, 224, 224]
+
[1, 3, 1, 1]

Common in image normalization.

============================================================
IMPORTANT DEEP LEARNING CONNECTION
============================================================

Broadcasting appears constantly in:

- normalization
- attention
- embeddings
- masking
- convolution systems
- transformer architectures

Understanding broadcasting deeply
is foundational for modern AI systems.

============================================================
MOST IMPORTANT INTUITION
============================================================

Broadcasting is not merely:

    automatic expansion

It is:

    structured tensor alignment

between compatible geometries.

============================================================
VECTOR + SCALAR BROADCASTING
============================================================

A scalar can broadcast across
every element of a tensor.

In [4]:

print("\n" + "=" * 80)
print("VECTOR + SCALAR BROADCASTING")
print("=" * 80)

vector = torch.tensor([1, 2, 3])

scalar = 10

print(f"vector:\n{vector}")

print(f"\nscalar:\n{scalar}")

result = vector + scalar

print(f"\nresult:\n{result}")

print("\nObservation:")

print(
    "The scalar value expands implicitly "
    "across every tensor element."
)


VECTOR + SCALAR BROADCASTING
vector:
tensor([1, 2, 3])

scalar:
10

result:
tensor([11, 12, 13])

Observation:
The scalar value expands implicitly across every tensor element.


In [5]:
# ============================================================
# MATRIX + VECTOR BROADCASTING
# ============================================================

# Here the vector broadcasts across rows.

print("\n" + "=" * 80)
print("MATRIX + VECTOR BROADCASTING")
print("=" * 80)

matrix = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

vector = torch.tensor([10, 20, 30])

print(f"matrix shape : {matrix.shape}")

print(f"vector shape : {vector.shape}")

print(f"\nmatrix:\n{matrix}")

print(f"\nvector:\n{vector}")

result = matrix + vector

print(f"\nresult:\n{result}")

print("\nObservation:")

print(
    "The vector broadcasts across "
    "each row of the matrix."
)


MATRIX + VECTOR BROADCASTING
matrix shape : torch.Size([2, 3])
vector shape : torch.Size([3])

matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

vector:
tensor([10, 20, 30])

result:
tensor([[11, 22, 33],
        [14, 25, 36]])

Observation:
The vector broadcasts across each row of the matrix.


In [6]:
# ============================================================
# UNSQUEEZE FOR BROADCASTING
# ============================================================

# unsqueeze() adds a singleton dimension.

print("\n" + "=" * 80)
print("UNSQUEEZE FOR BROADCASTING")
print("=" * 80)

tensor = torch.tensor([1, 2, 3])

print(f"original tensor shape : {tensor.shape}")

unsqueezed_tensor = tensor.unsqueeze(0)

print(
    f"unsqueezed tensor shape : "
    f"{unsqueezed_tensor.shape}"
)

print(f"\nunsqueezed tensor:\n{unsqueezed_tensor}")

print("\nObservation:")

print(
    "unsqueeze() introduces a new dimension "
    "without changing tensor values."
)


UNSQUEEZE FOR BROADCASTING
original tensor shape : torch.Size([3])
unsqueezed tensor shape : torch.Size([1, 3])

unsqueezed tensor:
tensor([[1, 2, 3]])

Observation:
unsqueeze() introduces a new dimension without changing tensor values.


In [7]:
# ============================================================
# COLUMN-WISE BROADCASTING
# ============================================================

# Broadcasting can also occur across columns.

print("\n" + "=" * 80)
print("COLUMN-WISE BROADCASTING")
print("=" * 80)

matrix = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

column_vector = torch.tensor(
    [
        [10],
        [20]
    ]
)

print(f"matrix shape        : {matrix.shape}")

print(
    f"column vector shape : "
    f"{column_vector.shape}"
)

print(f"\nmatrix:\n{matrix}")

print(f"\ncolumn vector:\n{column_vector}")

result = matrix + column_vector

print(f"\nresult:\n{result}")

print("\nObservation:")

print(
    "The singleton dimension expands "
    "across columns."
)


COLUMN-WISE BROADCASTING
matrix shape        : torch.Size([2, 3])
column vector shape : torch.Size([2, 1])

matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

column vector:
tensor([[10],
        [20]])

result:
tensor([[11, 12, 13],
        [24, 25, 26]])

Observation:
The singleton dimension expands across columns.


In [8]:
# ============================================================
# EXPLICIT EXPANSION
# ============================================================

# expand() creates a broadcasted view
# without copying memory.

print("\n" + "=" * 80)
print("EXPLICIT EXPANSION")
print("=" * 80)

tensor = torch.tensor([[1, 2, 3]])

print(f"original shape : {tensor.shape}")

expanded_tensor = tensor.expand(4, 3)

print(f"expanded shape : {expanded_tensor.shape}")

print(f"\nexpanded tensor:\n{expanded_tensor}")

print("\nObservation:")

print(
    "expand() creates virtual expansion "
    "without physically copying tensor data."
)


EXPLICIT EXPANSION
original shape : torch.Size([1, 3])
expanded shape : torch.Size([4, 3])

expanded tensor:
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

Observation:
expand() creates virtual expansion without physically copying tensor data.


In [9]:
# ============================================================
# REPEAT VS EXPAND
# ============================================================

# repeat() physically copies memory.

print("\n" + "=" * 80)
print("REPEAT VS EXPAND")
print("=" * 80)

tensor = torch.tensor([[1, 2, 3]])

expanded = tensor.expand(4, 3)

repeated = tensor.repeat(4, 1)

print(f"expanded shape : {expanded.shape}")

print(f"repeated shape : {repeated.shape}")

print(f"\nexpanded tensor:\n{expanded}")

print(f"\nrepeated tensor:\n{repeated}")

print("\nObservation:")

print(
    "expand() creates virtual broadcasting.\n"
    "repeat() physically duplicates data."
)


REPEAT VS EXPAND
expanded shape : torch.Size([4, 3])
repeated shape : torch.Size([4, 3])

expanded tensor:
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

repeated tensor:
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

Observation:
expand() creates virtual broadcasting.
repeat() physically duplicates data.


In [10]:
# ============================================================
# MEMORY COMPARISON
# ============================================================

print("\n" + "=" * 80)
print("MEMORY COMPARISON")
print("=" * 80)

print(
    f"Original Storage Size : "
    f"{tensor.storage().size()}"
)

print(
    f"Expanded Storage Size : "
    f"{expanded.storage().size()}"
)

print(
    f"Repeated Storage Size : "
    f"{repeated.storage().size()}"
)

print("\nObservation:")

print(
    "expand() reuses memory.\n"
    "repeat() allocates additional memory."
)


MEMORY COMPARISON
Original Storage Size : 3
Expanded Storage Size : 3
Repeated Storage Size : 12

Observation:
expand() reuses memory.
repeat() allocates additional memory.


/tmp/ipykernel_26432/2072338864.py:11: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  f"{tensor.storage().size()}"


In [11]:
# ============================================================
# HIGHER DIMENSION BROADCASTING
# ============================================================

# Broadcasting becomes extremely important
# in deep learning systems.

print("\n" + "=" * 80)
print("HIGHER DIMENSION BROADCASTING")
print("=" * 80)

batch_tensor = torch.randn(
    2, 3, 4
)

normalization_tensor = torch.randn(
    1, 3, 1
)

print(
    f"batch tensor shape : "
    f"{batch_tensor.shape}"
)

print(
    f"normalization tensor shape : "
    f"{normalization_tensor.shape}"
)

result = batch_tensor + normalization_tensor

print(f"\nresult shape : {result.shape}")

print("\nObservation:")

print(
    "Singleton dimensions broadcast across:\n"
    "- batch dimension\n"
    "- spatial dimension"
)


HIGHER DIMENSION BROADCASTING
batch tensor shape : torch.Size([2, 3, 4])
normalization tensor shape : torch.Size([1, 3, 1])

result shape : torch.Size([2, 3, 4])

Observation:
Singleton dimensions broadcast across:
- batch dimension
- spatial dimension


In [12]:
# ============================================================
# BROADCASTING FAILURE EXAMPLE
# ============================================================

print("\n" + "=" * 80)
print("BROADCASTING FAILURE EXAMPLE")
print("=" * 80)

a = torch.randn(2, 3)

b = torch.randn(4, 3)

print(f"a shape : {a.shape}")

print(f"b shape : {b.shape}")

try:

    result = a + b

except Exception as error:

    print("\nBroadcasting Failed.")

    print(f"\nError:\n{error}")

    print("\nObservation:")

    print(
        "Dimensions are incompatible because:\n"
        "2 cannot broadcast with 4"
    )


BROADCASTING FAILURE EXAMPLE
a shape : torch.Size([2, 3])
b shape : torch.Size([4, 3])

Broadcasting Failed.

Error:
The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0

Observation:
Dimensions are incompatible because:
2 cannot broadcast with 4


In [13]:
# ============================================================
# BROADCASTING VISUALIZATION
# ============================================================

print("\n" + "=" * 80)
print("BROADCASTING VISUALIZATION")
print("=" * 80)

print(
    """
Example:

    Tensor A : [3, 4]
    Tensor B : [1, 4]

Alignment:

        [3, 4]
        [1, 4]
         ↓
        [3, 4]

The singleton dimension expands
to match compatible geometry.
"""
)


BROADCASTING VISUALIZATION

Example:

    Tensor A : [3, 4]
    Tensor B : [1, 4]

Alignment:

        [3, 4]
        [1, 4]
         ↓
        [3, 4]

The singleton dimension expands
to match compatible geometry.



In [14]:
# ============================================================
# FINAL CONCEPTUAL SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("FINAL CONCEPTUAL SUMMARY")
print("=" * 80)

print(
    """
Broadcasting is one of the most important
ideas in tensor systems.

It enables:

- efficient tensor interaction
- implicit geometric alignment
- scalable deep learning computation

Broadcasting is not merely:

    automatic expansion

It is:

    structured tensor compatibility negotiation
"""
)


FINAL CONCEPTUAL SUMMARY

Broadcasting is one of the most important
ideas in tensor systems.

It enables:

- efficient tensor interaction
- implicit geometric alignment
- scalable deep learning computation

Broadcasting is not merely:

    automatic expansion

It is:

    structured tensor compatibility negotiation

