# Step 04 — Receptive Fields

# Core Philosophy

A receptive field defines:


    how much of the input tensor
    influences a representation.


If you completed the previous modules carefully,
you already understand that convolution operates
using two important components:

    1. the local region of the tensor being observed
    2. the convolution kernel (interaction rule)

The local region being observed becomes the starting point
of the receptive field.

As layers stack deeper, this influence region grows.

---

In convolution systems:

    * shallow layers observe local regions
    * deeper layers observe larger regions

If this sounds too technical, think about drawing an animal.

At first, you focus on small local structures:

    * eyes
    * claws
    * tail
    * ears

At this stage, your observation scope is limited.

As you continue drawing, you gradually combine these
local structures into larger representations.

Eventually, you understand:

    * body structure
    * posture
    * spatial proportions
    * full animal composition

This progression is very similar to convolution systems.

Early convolution layers learn:


    local structures


Deeper layers gradually construct:

    larger contextual understanding

This creates:

    hierarchical interaction growth

---

# Important Conceptual Insight

A neuron in a deep convolution layer
does NOT observe:

    a single pixel

It observes:

    an accumulated interaction history

This is one of the most important ideas
behind hierarchical representation learning.

---

# Core Intuition

Layer depth controls:

    interaction scope

As convolution layers stack:

    local interactions
        ↓
    regional interactions
        ↓
    global structures

This allows deep networks to gradually form:

- texture representations
- shape representations
- object representations
- semantic representations

---

# Mathematical Intuition

For stacked convolutions:

Each layer expands the region of influence.

Example:

Kernel size = 3

Layer 1:
    receptive field = 3

Layer 2:
    receptive field = 5

Layer 3:
    receptive field = 7

General intuition:

"""
# Receptive field growth intuition
# receptive_field_next =
# receptive_field_current + (kernel_size - 1)

"""
Thus deeper layers accumulate:

    larger interaction regions

---

# Geometric Interpretation

Convolution layers propagate:

    local interaction influence

through the tensor field.

This creates:

    progressively expanding observation geometry

---

# In This Step

We will explore:

1. local receptive fields
2. receptive field growth
3. stacked convolution systems
4. hierarchical interaction geometry
5. feature influence propagation
6. deep representation emergence

In [1]:

import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(42)

# 1. Creating a Simple Spatial Tensor

We create a small tensor with:

    a strong activation region

This helps visualize:

    how information propagates
    through convolution layers

In [2]:

x = torch.tensor([
    [0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 1., 1., 1., 0., 0.],
    [0., 0., 1., 5., 1., 0., 0.],
    [0., 0., 1., 1., 1., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0.]
])

print("Input Tensor:")
print(x)

Input Tensor:
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 1., 0., 0.],
        [0., 0., 1., 5., 1., 0., 0.],
        [0., 0., 1., 1., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])


# 2. Conv2D Tensor Format

PyTorch expects:

    [batch, channels, height, width]

In [3]:

x_conv = x.reshape(1, 1, 7, 7)

print("Input Shape:")
print(x_conv.shape)

Input Shape:
torch.Size([1, 1, 7, 7])


# 3. First Convolution Layer

Kernel size:

    3 × 3

This layer observes:

    local neighborhoods only

Each output position depends on:

    a small interaction region

This creates the first receptive field.

In [4]:

conv1 = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    bias=False
)

# 4. Assigning Simple Interaction Weights

We use:

    averaging-style interaction

This helps clearly visualize:

    information propagation

In [5]:

with torch.no_grad():

    conv1.weight[:] = torch.tensor([
        [
            [
                [1/9, 1/9, 1/9],
                [1/9, 1/9, 1/9],
                [1/9, 1/9, 1/9]
            ]
        ]
    ])

print("Layer 1 Kernel:")
print(conv1.weight)

Layer 1 Kernel:
Parameter containing:
tensor([[[[0.1111, 0.1111, 0.1111],
          [0.1111, 0.1111, 0.1111],
          [0.1111, 0.1111, 0.1111]]]], requires_grad=True)


# 5. Running First Convolution

The first layer creates:

    local interaction aggregation

Each output position sees:

    only a small local region

In [6]:

y1 = conv1(x_conv)

print("Layer 1 Output:")
print(y1.squeeze())

print("\nLayer 1 Output Shape:")
print(y1.shape)

Layer 1 Output:
tensor([[0.1111, 0.2222, 0.3333, 0.2222, 0.1111],
        [0.2222, 0.8889, 1.1111, 0.8889, 0.2222],
        [0.3333, 1.1111, 1.4444, 1.1111, 0.3333],
        [0.2222, 0.8889, 1.1111, 0.8889, 0.2222],
        [0.1111, 0.2222, 0.3333, 0.2222, 0.1111]], grad_fn=<SqueezeBackward0>)

Layer 1 Output Shape:
torch.Size([1, 1, 5, 5])


# Understanding Layer 1

At this stage:

    receptive field = 3 × 3

Each output value depends only on:

    a local neighborhood

The system still has:

    highly localized awareness

# 6. Second Convolution Layer

We now stack another convolution layer.

Important insight:

The second layer no longer sees:

    raw pixels only

It sees:

    responses generated by Layer 1

Thus receptive fields expand.

In [7]:

conv2 = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    bias=False
)

# 7. Assigning Second Layer Weights

Again we use:

    averaging interaction geometry

This allows us to focus on:

    receptive field expansion

In [8]:

with torch.no_grad():

    conv2.weight[:] = torch.tensor([
        [
            [
                [1/9, 1/9, 1/9],
                [1/9, 1/9, 1/9],
                [1/9, 1/9, 1/9]
            ]
        ]
    ])

print("Layer 2 Kernel:")
print(conv2.weight)

Layer 2 Kernel:
Parameter containing:
tensor([[[[0.1111, 0.1111, 0.1111],
          [0.1111, 0.1111, 0.1111],
          [0.1111, 0.1111, 0.1111]]]], requires_grad=True)


# 8. Running Second Convolution

Now Layer 2 aggregates:

    Layer 1 interaction responses

This creates:

    larger interaction influence regions

In [9]:

y2 = conv2(y1)

print("Layer 2 Output:")
print(y2.squeeze())

print("\nLayer 2 Output Shape:")
print(y2.shape)

Layer 2 Output:
tensor([[0.6420, 0.8148, 0.6420],
        [0.8148, 1.0494, 0.8148],
        [0.6420, 0.8148, 0.6420]], grad_fn=<SqueezeBackward0>)

Layer 2 Output Shape:
torch.Size([1, 1, 3, 3])


# Understanding Receptive Field Expansion

Layer 1:
    each neuron sees 3×3 region

Layer 2:
    each neuron indirectly sees 5×5 region

Why?

Because Layer 2 observes:

    Layer 1 outputs

And Layer 1 outputs already summarize:

    local neighborhoods

Thus interaction influence accumulates.

# 9. Visualizing Receptive Field Growth

Important progression:

Input
    ↓
Local interactions
    ↓
Aggregated local structure
    ↓
Larger interaction awareness
    ↓
Hierarchical representation

This is one of the foundational mechanisms
behind deep learning systems.

In [10]:

print("Original Input Shape:")
print(x.shape)

print("\nLayer 1 Shape:")
print(y1.squeeze().shape)

print("\nLayer 2 Shape:")
print(y2.squeeze().shape)

Original Input Shape:
torch.Size([7, 7])

Layer 1 Shape:
torch.Size([5, 5])

Layer 2 Shape:
torch.Size([3, 3])


# 10. Conceptual Receptive Field Geometry

Suppose we observe:

    one neuron in Layer 2

That neuron depends on:

    multiple Layer 1 neurons

Each Layer 1 neuron depends on:

    multiple input pixels

Thus the Layer 2 neuron indirectly depends on:

    a much larger spatial region

This accumulated dependency region is:

    the receptive field

# 11. Hierarchical Representation Learning

This receptive field growth enables:

Shallow layers:
    local textures
    edges
    simple patterns

Middle layers:
    motifs
    structures
    arrangements

Deep layers:
    semantic compositions
    object-level representations

The network gradually builds:

    larger interaction awareness

# 12. Receptive Fields and Intelligence

This is one of the deepest principles
in convolution systems:

    intelligence emerges through
    progressive interaction accumulation

Deep networks do not suddenly become intelligent.

They gradually expand:

- interaction scope
- representation hierarchy
- structural awareness

through stacked local operations.

# Final Conceptual Understanding

A receptive field represents:

    the region of influence
    for a representation

Deeper layers accumulate:

    larger interaction histories

This allows neural systems to progressively form:

- local understanding
- regional understanding
- global understanding

through repeated local aggregation.

---

# Deep Insight

One of the most profound ideas in deep learning:

    Global representations emerge
    from accumulated local interactions.

Receptive fields are one of the clearest
demonstrations of this principle.