# Step 03 — Kernels as Local Patterns

# Core Philosophy

Kernels are not magical feature detectors.

Kernels are:

    localized interaction operators

A kernel defines:

    how neighboring tensor values interact
(I believe that you understand what a neighborhood is.
If any confusion arises just do a simple search to see
how neiborhood is defined)

Different kernels create different kinds of:

- interaction sensitivity
- local aggregation behavior
- spatial response patterns

---

# Important Conceptual Shift
Let's build perspective:
Most of the time from engineering point of view
we perceive kernels as:

    edge detectors
    blur filters
    sharpen filters

But a deeper interpretation is:

    kernels encode local interaction rules

The observed patterns emerge from:

    tensor neighborhood interactions

---

# Core Mathematical Formulation

For Conv2D:

y(i,j) = Σ Σ x(i+m,j+n) * w(m,n)

"""
# Mathematical representation
# y(i,j) = sum_m (sum_n (x(i+m,j+n) w(m,n)))

"""
Where:

- x = input tensor
- w = kernel
- y = output response field

The kernel defines:

    interaction weighting geometry

---

# Geometric Interpretation

A kernel slides through local regions.

At each location:

    local tensor neighborhood
        ↓
    weighted interaction
        ↓
    response generation

Different kernels emphasize different:

- spatial relationships
- directional structures
- interaction behaviors

---

# In This Step

We will explore:

1. kernels as interaction systems
2. edge-sensitive kernels
3. averaging kernels
4. sharpening kernels
5. directional interaction behavior
6. feature response geometry

In [1]:

import torch
import torch.nn.functional as F

torch.manual_seed(42)

# 1. Creating a Spatial Tensor

This tensor represents:

    a geometric interaction surface

We intentionally create:

- low values on left
- high values on right

This creates:

    strong spatial transitions

In [2]:

x = torch.tensor([
    [1., 1., 1., 1., 1.],
    [1., 1., 1., 1., 1.],
    [1., 1., 10., 10., 10.],
    [1., 1., 10., 10., 10.],
    [1., 1., 10., 10., 10.]
])

print("Input Tensor:")
print(x)

Input Tensor:
tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1., 10., 10., 10.],
        [ 1.,  1., 10., 10., 10.],
        [ 1.,  1., 10., 10., 10.]])


# 2. Converting to Conv2D Format

PyTorch Conv2D expects:

    [batch, channels, height, width]

In [3]:

x_conv = x.reshape(1, 1, 5, 5)

print("Conv Tensor Shape:")
print(x_conv.shape)

Conv Tensor Shape:
torch.Size([1, 1, 5, 5])


# 3. Kernel 1 — Vertical Difference Sensitivity

Kernel:

    [[ 1,  0, -1],
     [ 1,  0, -1],
     [ 1,  0, -1]]

This kernel becomes sensitive to:

    horizontal spatial changes

Conceptually:

    compare left vs right neighborhoods
    If abrupt changes are there, the kernel
    can feel it.
For curious readers, it is called Prewitt vertical edge filter.

This is NOT magic edge detection.

It is:

    directional interaction sensitivity

In [4]:

vertical_kernel = torch.tensor([
    [1., 0., -1.],
    [1., 0., -1.],
    [1., 0., -1.]
])

print("Vertical Interaction Kernel:")
print(vertical_kernel)

Vertical Interaction Kernel:
tensor([[ 1.,  0., -1.],
        [ 1.,  0., -1.],
        [ 1.,  0., -1.]])


# 4. Applying Vertical Interaction Kernel

The kernel scans spatial neighborhoods.

Each output value becomes:

    local directional interaction response

In [5]:

vertical_output = F.conv2d(
    x_conv,
    vertical_kernel.reshape(1, 1, 3, 3)
)

print("Vertical Interaction Response:")
print(vertical_output.squeeze())

Vertical Interaction Response:
tensor([[ -9.,  -9.,   0.],
        [-18., -18.,   0.],
        [-27., -27.,   0.]])


# Understanding the Output

High magnitude values indicate:

    strong directional differences

The kernel strongly responds where:

    local left-right structure changes rapidly

This demonstrates:

    kernels encode interaction sensitivity

# 5. Kernel 2 — Averaging Kernel

Kernel:

    every position contributes equally

This creates:

    local smoothing behavior

Conceptually:

    neighborhood averaging interaction

In [6]:

average_kernel = torch.tensor([
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9]
])

print("Averaging Kernel:")
print(average_kernel)

Averaging Kernel:
tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])


# 6. Applying Averaging Kernel

The kernel aggregates:

    local regional statistics

This reduces:

- sharp variation
- local discontinuities
- spatial contrast

In [7]:

average_output = F.conv2d(
    x_conv,
    average_kernel.reshape(1, 1, 3, 3)
)

print("Averaging Response:")
print(average_output.squeeze())

Averaging Response:
tensor([[ 2.0000,  3.0000,  4.0000],
        [ 3.0000,  5.0000,  7.0000],
        [ 4.0000,  7.0000, 10.0000]])


# Understanding Averaging Behavior

The output becomes smoother because:

    neighboring values cooperate. Means neighbouring values
    are added together ana averaged.

The kernel promotes:

    local consistency

This demonstrates:

    kernels shape interaction dynamics

# 7. Kernel 3 — Sharpening Kernel

Kernel:

    [[ 0, -1,  0],
     [-1,  5, -1],
     [ 0, -1,  0]]

Conceptually:

    amplify local contrast structure

The center becomes dominant while
neighboring regions are suppressed.

In [8]:

sharpen_kernel = torch.tensor([
    [0., -1., 0.],
    [-1., 5., -1.],
    [0., -1., 0.]
])

print("Sharpen Kernel:")
print(sharpen_kernel)

Sharpen Kernel:
tensor([[ 0., -1.,  0.],
        [-1.,  5., -1.],
        [ 0., -1.,  0.]])


# 8. Applying Sharpening Kernel

This interaction rule increases:

    local structural emphasis

In [9]:

sharpen_output = F.conv2d(
    x_conv,
    sharpen_kernel.reshape(1, 1, 3, 3)
)

print("Sharpened Response:")
print(sharpen_output.squeeze())

Sharpened Response:
tensor([[ 1., -8., -8.],
        [-8., 28., 19.],
        [-8., 19., 10.]])


# Understanding Sharpening Behavior

The kernel strengthens:

    local contrast dominance

Important idea:

Different kernels produce different:

- interaction geometries
- response behaviors
- representation sensitivities

# 9. Comparing Multiple Kernels

Observe carefully:

Same input tensor.
Different kernels.
Different response fields.

Why?

Because kernels define:

    interaction behavior

The input remains identical.

Only the local interaction rule changes.

In [10]:

print("Input Tensor:")
print(x)

print("\nVertical Interaction Response:")
print(vertical_output.squeeze())

print("\nAveraging Response:")
print(average_output.squeeze())

print("\nSharpened Response:")
print(sharpen_output.squeeze())

Input Tensor:
tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1., 10., 10., 10.],
        [ 1.,  1., 10., 10., 10.],
        [ 1.,  1., 10., 10., 10.]])

Vertical Interaction Response:
tensor([[ -9.,  -9.,   0.],
        [-18., -18.,   0.],
        [-27., -27.,   0.]])

Averaging Response:
tensor([[ 2.0000,  3.0000,  4.0000],
        [ 3.0000,  5.0000,  7.0000],
        [ 4.0000,  7.0000, 10.0000]])

Sharpened Response:
tensor([[ 1., -8., -8.],
        [-8., 28., 19.],
        [-8., 19., 10.]])


# 10. Kernels as Learned Interaction Systems

In deep learning:

    kernels are NOT manually designed

Neural networks learn kernels automatically.

During training:

- useful interaction rules emerge
- response sensitivity evolves
- representation systems form

The network gradually learns:

    which local interactions matter

This is a foundational principle behind:

- CNNs
- vision systems
- audio systems
- scientific tensor models

---

# Local Pattern Formation

A kernel can become sensitive to:

- orientation
- texture
- local contrast
- frequency patterns
- spatial continuity

But these are emergent interaction behaviors,
not symbolic understanding.

# 11. Interaction Geometry Perspective

A convolution kernel behaves like:

    a localized interaction operator

It defines:

- what neighboring relationships matter
- how aggregation occurs
- which structures become amplified

Feature maps therefore become:

    interaction response surfaces

This is a much deeper interpretation than:

    "the network detects edges"

---

# Deep Insight

One of the most important ideas in deep learning:

    Representation emerges from interaction sensitivity.

Kernels define:

    what local structures become visible