# Step 06 — Padding and Boundary Systems

# Core Philosophy

Padding is not merely:

    "adding extra zeros"

Padding controls:

    boundary interaction geometry

In convolution systems, kernels interact with:

    local spatial neighborhoods

But tensors have boundaries.

At the edges:

- neighborhoods become incomplete
- interaction symmetry breaks
- spatial information collapses

Padding helps stabilize these boundary interactions.

---

# Important Intuition

Without padding:

    boundary regions lose influence

As convolutions stack:

- tensor dimensions shrink
- edge information disappears
- spatial coverage becomes uneven

Padding preserves:

- interaction continuity
- spatial symmetry
- boundary participation

---

# Boundary Interaction Problem

Suppose we use:

    kernel size = 3

A center pixel has:

    full neighborhood access

But edge pixels do not.

Example:

Center region:
    full 3×3 interaction neighborhood

Corner region:
    incomplete neighborhood

Thus boundary regions become:

    structurally disadvantaged

Padding compensates for this imbalance.

---

# Geometric Interpretation

Padding extends the tensor field.

This creates:

    artificial boundary support regions

The convolution kernel can now maintain:

    consistent interaction geometry

across the spatial field.

---

# Types of Padding

Common padding strategies:

- zero padding
- reflection padding
- replication padding

Each strategy creates different:

    boundary interaction behavior

In this module we focus mainly on:

    zero padding

because it is the most common introductory form.

---

# Mathematical Intuition

For Conv2D output size:

"""
# Output size formula
# output_size =
# ((input_size - kernel_size + 2*padding) / stride) + 1

"""
Padding increases:

    effective spatial size

which helps preserve:

    output resolution

---

# Important Insight

Padding is fundamentally about:

    preserving interaction opportunity

especially near boundaries.

This becomes very important in:

- segmentation systems
- medical imaging
- scientific simulations
- dense prediction systems

where edge information matters significantly.

---

# In This Step

We will explore:

1. convolution without padding
2. boundary information collapse
3. zero padding
4. spatial symmetry preservation
5. output size stabilization
6. boundary interaction systems

In [1]:

import torch
import torch.nn.functional as F

torch.manual_seed(42)

# 1. Creating a Spatial Tensor

We create a simple tensor field
with clear spatial structure.

This helps visualize:

- shrinking geometry
- edge interaction behavior
- padding influence

In [2]:

x = torch.tensor([
    [1., 2., 3., 4., 5.],
    [6., 7., 8., 9., 10.],
    [11., 12., 13., 14., 15.],
    [16., 17., 18., 19., 20.],
    [21., 22., 23., 24., 25.]
])

print("Input Tensor:")
print(x)

print("\nInput Shape:")
print(x.shape)

Input Tensor:
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.]])

Input Shape:
torch.Size([5, 5])


# 2. Converting to Conv2D Format

PyTorch expects:

    [batch, channels, height, width]

In [3]:

x_conv = x.reshape(1, 1, 5, 5)

print("Conv Tensor Shape:")
print(x_conv.shape)

Conv Tensor Shape:
torch.Size([1, 1, 5, 5])


# 3. Creating a Simple Kernel

We use a simple averaging kernel.

This allows us to focus on:

    boundary interaction behavior

rather than feature extraction complexity.

In [4]:

kernel = torch.tensor([
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9]
])

print("Kernel:")
print(kernel)

Kernel:
tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])


# 4. Convolution Without Padding

Padding = 0

The kernel cannot move beyond
valid spatial neighborhoods.

Thus edge regions become excluded.

In [5]:

output_no_padding = F.conv2d(
    x_conv,
    kernel.reshape(1, 1, 3, 3),
    padding=0
)

print("Output Without Padding:")
print(output_no_padding.squeeze())

print("\nOutput Shape:")
print(output_no_padding.squeeze().shape)

Output Without Padding:
tensor([[ 7.0000,  8.0000,  9.0000],
        [12.0000, 13.0000, 14.0000],
        [17.0000, 18.0000, 19.0000]])

Output Shape:
torch.Size([3, 3])


# Understanding No Padding Behavior

Observe:

Input shape:
    5 × 5

Output shape:
    3 × 3

Why?

Because boundary regions cannot support:

    full interaction neighborhoods

Thus spatial dimensions collapse.

Important consequence:

    edge information loses participation

# 5. Visualizing Boundary Exclusion

Without padding:

Kernel only visits positions where:

    full 3×3 interaction is possible

Corner regions become excluded from:

    centered interaction participation

In [6]:

print("Valid Kernel Positions Without Padding")
print("--------------------------------------")

for i in range(0, 5 - 3 + 1):

    for j in range(0, 5 - 3 + 1):

        print(f"Kernel center region around ({i+1},{j+1})")

Valid Kernel Positions Without Padding
--------------------------------------
Kernel center region around (1,1)
Kernel center region around (1,2)
Kernel center region around (1,3)
Kernel center region around (2,1)
Kernel center region around (2,2)
Kernel center region around (2,3)
Kernel center region around (3,1)
Kernel center region around (3,2)
Kernel center region around (3,3)


# 6. Applying Zero Padding

Padding = 1

This adds:

    artificial boundary support

around the tensor field.

Now edge regions gain:

    additional interaction space

In [7]:

output_with_padding = F.conv2d(
    x_conv,
    kernel.reshape(1, 1, 3, 3),
    padding=1
)

print("Output With Padding:")
print(output_with_padding.squeeze())

print("\nOutput Shape:")
print(output_with_padding.squeeze().shape)

Output With Padding:
tensor([[ 1.7778,  3.0000,  3.6667,  4.3333,  3.1111],
        [ 4.3333,  7.0000,  8.0000,  9.0000,  6.3333],
        [ 7.6667, 12.0000, 13.0000, 14.0000,  9.6667],
        [11.0000, 17.0000, 18.0000, 19.0000, 13.0000],
        [ 8.4444, 13.0000, 13.6667, 14.3333,  9.7778]])

Output Shape:
torch.Size([5, 5])


# Understanding Padding Behavior

Observe:

Input shape:
    5 × 5

Output shape:
    5 × 5

Padding preserves:

    spatial interaction symmetry

Now edge regions participate more equally
in convolution operations.

# 7. Visualizing Explicit Zero Padding

PyTorch internally adds:

    boundary zeros

Let us inspect this directly.

In [8]:

padded_tensor = F.pad(
    x_conv,
    pad=(1, 1, 1, 1),  # left, right, top, bottom
    mode="constant",
    value=0
)

print("Explicitly Padded Tensor:")
print(padded_tensor.squeeze())

print("\nPadded Shape:")
print(padded_tensor.squeeze().shape)

Explicitly Padded Tensor:
tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  0.],
        [ 0.,  6.,  7.,  8.,  9., 10.,  0.],
        [ 0., 11., 12., 13., 14., 15.,  0.],
        [ 0., 16., 17., 18., 19., 20.,  0.],
        [ 0., 21., 22., 23., 24., 25.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

Padded Shape:
torch.Size([7, 7])


# Important Observation

The tensor field is now extended.

This creates:

    artificial interaction support regions

The kernel can now maintain:

    more consistent traversal geometry

# 8. Comparing No Padding vs Padding

Without padding:

- shrinking representations
- boundary exclusion
- reduced interaction coverage

With padding:

- stable dimensions
- improved edge participation
- balanced interaction geometry

In [9]:

print("No Padding Output Shape:")
print(output_no_padding.squeeze().shape)

print("\nWith Padding Output Shape:")
print(output_with_padding.squeeze().shape)

No Padding Output Shape:
torch.Size([3, 3])

With Padding Output Shape:
torch.Size([5, 5])


# 9. Padding and Deep Networks

In deep CNN systems:

Repeated convolution without padding causes:

    progressive spatial collapse

Example:

Layer 1:
    64 × 64 → 62 × 62

Layer 2:
    62 × 62 → 60 × 60

Layer 3:
    60 × 60 → 58 × 58

Eventually:

    boundary information disappears

Padding prevents excessive geometry collapse.

# 10. Padding as Boundary Stabilization

A deeper interpretation:

Padding preserves:

    interaction opportunity symmetry

Without padding:

- center regions dominate
- edge regions become underrepresented

Padding helps maintain:

    balanced spatial influence

This is extremely important in:

- segmentation systems
- dense prediction systems
- scientific imaging
- physical simulation tensors

# 11. Reflection Padding Intuition

Zero padding introduces:

    artificial emptiness

Alternative strategies exist.

Reflection padding:

    mirrors boundary structure

Replication padding:

    repeats edge values

Different padding methods create different:

    boundary interaction assumptions

# Final Conceptual Understanding

Padding is fundamentally:

    boundary interaction stabilization

It preserves:

- spatial continuity
- interaction symmetry
- representation geometry

Padding ensures that convolution systems can maintain:

    balanced spatial aggregation

even near tensor boundaries.

---

# Deep Insight

One of the deepest ideas in tensor systems:

    Boundaries influence representation quality.

Padding demonstrates that even artificial
interaction support regions can significantly
affect representation behavior.