# Step 07 — Feature Maps

# Core Philosophy




Feature maps are not merely:

    "detected features"

Feature maps are:

    interaction response fields

A convolution kernel defines:

    a local interaction rule

As the kernel moves through the tensor field,
different regions respond differently.

The resulting tensor becomes:

    a spatial response map

showing how strongly each region reacts to
a particular interaction rule.

---
Here undertanding what a feature represents is 
quite essential. Otherwise later on when you 
will set threshold for decision making you will 
surely run into problem.
Let's explore this with a situation.

Features  refer to the measurable attributes or  variables.
So indeed you can measure something with a scale, but if you 
don't know what you are measuring how will you decide what to
do? 
Let's imagine you entered your friends house. You encountered
a clay cobra looking at you, hood spead, teeths are ready to bite you, eyes focused on your face
, to grab the opportunity to take revenge on behalf of its owner.
You jumped reflexively. Indeed at the
basic we human beings are simple reflex agents and nothing wrong
with that. It is indeed rational. After a moment you observed something.
Its hood is not moving. So you measured a feature: called movement, which can assume 
values from {true, false} domain.
Observing this your courage meter increased a little. You 
start observing it from right left. Its tail is at a fixed place for
sometime. So second feature:tail-position: fixed from {fixed, variable}.
Now probability of its not being actual Mr Snake or an artifical snake
increased quite a lot. But you don't want to assume black swan risk.
You saw your friend's grand father's stick at a corner. You took it
and poked the snake on its face. The snake is quiet and peaceful.
So third parameter snake-angry given poked-with-stick is also false.
Now you have a feature state:
{movement:false, tail-position:fixed, snake-angry given poked-with-stick:false}.
It's time to make decision: Next day you will take revenge with compounding
effect.
The pov is that you are not actually measuring the snake. You are measuring
some quantifiable parameters.

# Important Conceptual Shift

Most beginner explanations say:

    "CNN detects edges"

But a deeper interpretation is:

    convolution generates structured
    interaction response geometry

A feature map represents:

    response intensity distribution

across spatial regions.

---

# Geometric Interpretation

Input tensor:
    spatial interaction surface

Kernel:
    local interaction operator

Feature map:
    response field generated from interaction

Thus the process becomes:

    local structure
        ↓
    interaction
        ↓
    response intensity
        ↓
    representation field

---

# Important Insight

Different kernels generate different:

- interaction sensitivities
- spatial response patterns
- representation structures

Thus different feature maps capture different:

    aspects of tensor geometry

---

# Multi-Channel Perspective

Modern CNNs do not generate:

    one feature map

They generate:

    many parallel response fields

Each feature map learns different:

- spatial sensitivities
- interaction rules
- representation patterns

This creates:

    distributed representation systems

---

# Mathematical Intuition

For a convolution operation:

"""
# Convolution formulation
# y(i,j) = \sum_m \sum_n x(i+m,j+n) w(m,n)

"""
The feature map stores:

    interaction responses

for all spatial locations.

---

# In This Step

We will explore:

1. feature maps as response fields
2. different kernel sensitivities
3. multi-feature extraction
4. parallel representation systems
5. spatial response geometry
6. learned interaction behavior

In [1]:

import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(42)

# 1. Creating a Spatial Tensor

We create a tensor with:

- smooth regions
- strong transitions
- structured spatial variation

This helps visualize:

    different interaction responses

In [2]:

x = torch.tensor([
    [1., 1., 1., 1., 1., 1.],
    [1., 1., 1., 1., 1., 1.],
    [1., 1., 10., 10., 10., 10.],
    [1., 1., 10., 10., 10., 10.],
    [1., 1., 10., 10., 10., 10.],
    [1., 1., 10., 10., 10., 10.]
])

print("Input Tensor:")
print(x)

print("\nInput Shape:")
print(x.shape)

Input Tensor:
tensor([[ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1., 10., 10., 10., 10.],
        [ 1.,  1., 10., 10., 10., 10.],
        [ 1.,  1., 10., 10., 10., 10.],
        [ 1.,  1., 10., 10., 10., 10.]])

Input Shape:
torch.Size([6, 6])


# 2. Converting to Conv2D Format

PyTorch expects:

    [batch, channels, height, width]

In [3]:

x_conv = x.reshape(1, 1, 6, 6)

print("Conv Tensor Shape:")
print(x_conv.shape)

Conv Tensor Shape:
torch.Size([1, 1, 6, 6])


# 3. Vertical Interaction Kernel

This kernel becomes sensitive to:

    left-right spatial variation

Conceptually:

    directional interaction sensitivity

In [4]:

vertical_kernel = torch.tensor([
    [1., 0., -1.],
    [1., 0., -1.],
    [1., 0., -1.]
])

print("Vertical Kernel:")
print(vertical_kernel)

Vertical Kernel:
tensor([[ 1.,  0., -1.],
        [ 1.,  0., -1.],
        [ 1.,  0., -1.]])


# 4. Horizontal Interaction Kernel

This kernel becomes sensitive to:

    top-bottom spatial variation

Again:

    interaction sensitivity differs

In [5]:

horizontal_kernel = torch.tensor([
    [1., 1., 1.],
    [0., 0., 0.],
    [-1., -1., -1.]
])

print("Horizontal Kernel:")
print(horizontal_kernel)

Horizontal Kernel:
tensor([[ 1.,  1.,  1.],
        [ 0.,  0.,  0.],
        [-1., -1., -1.]])


# 5. Averaging Kernel

This kernel performs:

    local smoothing interaction

It responds to:

    regional consistency

In [6]:

average_kernel = torch.tensor([
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9]
])

print("Average Kernel:")
print(average_kernel)

Average Kernel:
tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])


# 6. Generating Feature Maps

Each kernel creates:

    a different response field

The same input tensor produces:

    different representations

depending on interaction rules.

In [7]:

vertical_feature_map = F.conv2d(
    x_conv,
    vertical_kernel.reshape(1, 1, 3, 3)
)

horizontal_feature_map = F.conv2d(
    x_conv,
    horizontal_kernel.reshape(1, 1, 3, 3)
)

average_feature_map = F.conv2d(
    x_conv,
    average_kernel.reshape(1, 1, 3, 3)
)

# 7. Vertical Response Field

This feature map shows:

    where horizontal spatial transitions occur

High responses indicate:

    strong directional contrast

In [8]:

print("Vertical Feature Map:")
print(vertical_feature_map.squeeze())

Vertical Feature Map:
tensor([[ -9.,  -9.,   0.,   0.],
        [-18., -18.,   0.,   0.],
        [-27., -27.,   0.,   0.],
        [-27., -27.,   0.,   0.]])


# 8. Horizontal Response Field

This feature map responds differently.

It emphasizes:

    vertical structural changes

In [9]:

print("Horizontal Feature Map:")
print(horizontal_feature_map.squeeze())

Horizontal Feature Map:
tensor([[ -9., -18., -27., -27.],
        [ -9., -18., -27., -27.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])


# 9. Averaging Response Field

This feature map performs:

    regional aggregation

The representation becomes smoother because:

    neighboring values cooperate

In [10]:

print("Average Feature Map:")
print(average_feature_map.squeeze())

Average Feature Map:
tensor([[ 2.0000,  3.0000,  4.0000,  4.0000],
        [ 3.0000,  5.0000,  7.0000,  7.0000],
        [ 4.0000,  7.0000, 10.0000, 10.0000],
        [ 4.0000,  7.0000, 10.0000, 10.0000]])


# Important Observation

Same input tensor.
Different kernels.
Different feature maps.

Why?

Because each kernel defines:

    different interaction behavior

Thus feature maps are fundamentally:

    response distributions

# 10. Multi-Feature Representation Systems

Modern CNNs use:

    many kernels simultaneously

Each kernel learns different:

- local interaction rules
- spatial sensitivities
- representation preferences

Thus networks build:

    distributed representation fields

In [11]:

multi_kernel = torch.stack([
    vertical_kernel,
    horizontal_kernel,
    average_kernel
])

multi_kernel = multi_kernel.unsqueeze(1)

print("Multi-Kernel Shape:")
print(multi_kernel.shape)

Multi-Kernel Shape:
torch.Size([3, 1, 3, 3])


# 11. Parallel Feature Map Generation

Now multiple kernels operate simultaneously.

The output contains:

    multiple response fields

This is one of the foundational mechanisms
behind convolutional representation learning.

In [12]:

multi_feature_maps = F.conv2d(
    x_conv,
    multi_kernel
)

print("Multi-Feature Map Shape:")
print(multi_feature_maps.shape)

Multi-Feature Map Shape:
torch.Size([1, 3, 4, 4])


# Output Shape Interpretation

Output shape:

    [batch, channels, height, width]

Important insight:

Each output channel becomes:

    a separate feature map

Thus output channels represent:

    parallel representation systems

In [13]:

print("Feature Map 1 — Vertical Response")
print(multi_feature_maps[0, 0])

print("\nFeature Map 2 — Horizontal Response")
print(multi_feature_maps[0, 1])

print("\nFeature Map 3 — Averaging Response")
print(multi_feature_maps[0, 2])

Feature Map 1 — Vertical Response
tensor([[ -9.,  -9.,   0.,   0.],
        [-18., -18.,   0.,   0.],
        [-27., -27.,   0.,   0.],
        [-27., -27.,   0.,   0.]])

Feature Map 2 — Horizontal Response
tensor([[ -9., -18., -27., -27.],
        [ -9., -18., -27., -27.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])

Feature Map 3 — Averaging Response
tensor([[ 2.0000,  3.0000,  4.0000,  4.0000],
        [ 3.0000,  5.0000,  7.0000,  7.0000],
        [ 4.0000,  7.0000, 10.0000, 10.0000],
        [ 4.0000,  7.0000, 10.0000, 10.0000]])


# 12. Feature Maps as Representation Fields

A feature map should not be viewed as:

    symbolic understanding

Instead it represents:

    spatial interaction response intensity

The network gradually learns:

    which local interactions matter

through training and optimization.

# 13. Hierarchical Feature Systems

Shallow feature maps often respond to:

- edges
- textures
- local contrast

Deeper feature maps respond to:

- structures
- arrangements
- semantic compositions

This hierarchy emerges through:

    repeated interaction aggregation

# 14. Feature Maps and Deep Learning

One of the most important ideas in CNNs:

Different kernels create different:

    representation perspectives

The network therefore develops:

    distributed spatial understanding

rather than one single representation.

# Final Conceptual Understanding

Feature maps are fundamentally:

    interaction response fields

A kernel defines:

    what local interactions matter

The feature map records:

    where those interactions occur strongly

Modern deep learning systems build intelligence through:

    many interacting response fields

operating simultaneously across tensor geometry.

---

# Deep Insight

One of the deepest principles in CNN systems:

    Representation emerges from
    structured interaction responses.

Feature maps are the spatial memory
of those interactions.